-- ============================================================================
-- 006_global_indicators.sql — worldwide coverage
--
-- Every series below was fetched and confirmed to return real observations
-- before being written here, on 2026-08-25. That matters more than usual: a
-- wrong series code does not error, it returns nothing, and an empty chart
-- reads as "no data" rather than "broken". This project has already been bitten
-- three times by exactly that.
--
-- DBnomics mirrors 93 national statistics agencies behind one API, which is why
-- coverage of the UK, EU, China, Japan and Australia needs configuration rather
-- than one adapter per country.
-- ============================================================================

INSERT INTO indicators (
  id, name, description, pillar, quantity_kind, cadence, confidence_tier,
  unit, unit_symbol, decimals, source_id, source_series_code, source_url,
  higher_is_better, has_country_dim, has_industry_dim, has_company_dim,
  refresh_interval, default_country_iso3
) VALUES

('dbn.Eurostat.isoc_eb_ai.A.GE10.C10-S951_X_K.E_AI_TANY.PC_ENT.EU27_2020',
 'Enterprises (10+ employees) using at least one AI technology, EU27',
 'The single best direct measurement of AI adoption in any economy in DBnomics: the share of EU firms actually using AI more than doubled from 8.1% in 2023 to 20.0% in 2025, giving a headline diffusion curve against which every productivity and employment series can be read.',
 'adoption', 'rate', 'annual', 'official',
 'Percentage of enterprises', NULL, 2, 'dbnomics', 'Eurostat/isoc_eb_ai/A.GE10.C10-S951_X_K.E_AI_TANY.PC_ENT.EU27_2020',
 'https://db.nomics.world/Eurostat/isoc_eb_ai/A.GE10.C10-S951_X_K.E_AI_TANY.PC_ENT.EU27_2020',
 NULL, FALSE, FALSE, FALSE, INTERVAL '1 day', NULL),

('dbn.Eurostat.isoc_eb_ain2.A.GE10.J62_J63.E_AI_TANY.PC_ENT.EU27_2020',
 'AI adoption by enterprises in computer programming, consultancy and information services, EU27',
 'Shows AI diffusion where it bites first — software and IT services went 28.2% (2021) to 65.7% (2025) — and the same dataset carries 50 NACE activities and 36 countries on identical codes, so one adapter pattern yields a full industry adoption matrix (manufacturing C 17.3%, construction F 10.8%, transport H 11.2% in 2025).',
 'adoption', 'rate', 'annual', 'official',
 'Percentage of enterprises', NULL, 2, 'dbnomics', 'Eurostat/isoc_eb_ain2/A.GE10.J62_J63.E_AI_TANY.PC_ENT.EU27_2020',
 'https://db.nomics.world/Eurostat/isoc_eb_ain2/A.GE10.J62_J63.E_AI_TANY.PC_ENT.EU27_2020',
 NULL, FALSE, FALSE, FALSE, INTERVAL '1 day', NULL),

('dbn.ONS.UNEM.JP9P.M',
 'UK job vacancies, Information & Communication sector',
 'The cleanest high-frequency labour signal for AI displacement in the UK: tech-sector vacancies ran at ~50k in 2001 and sit at 39k in June 2026, and monthly cadence catches turning points years before annual productivity data does.',
 'adoption', 'magnitude', 'monthly', 'official',
 'Thousands of vacancies (NA-sentinel strings present; filter ', NULL, 2, 'dbnomics', 'ONS/UNEM/JP9P.M',
 'https://db.nomics.world/ONS/UNEM/JP9P.M',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'GBR'),

('dbn.ONS.PRDY.DJR5.Q',
 'UK output per hour, Information & communication services (SIC07 J), index 2023=100',
 'The UK is absent from Eurostat''s industry productivity data after 2019, so this is the only way to test whether AI adoption is showing up as measured productivity in Britain''s most AI-exposed sector — and it runs to 2026-Q1, more current than anything else in the project.',
 'adoption', 'index', 'quarterly', 'official',
 'Index, 2023=100, seasonally adjusted (NA-sentinel strings pr', NULL, 2, 'dbnomics', 'ONS/PRDY/DJR5.Q',
 'https://db.nomics.world/ONS/PRDY/DJR5.Q',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'GBR'),

('dbn.Eurostat.isoc_eb_ai.A.GE10.C10-S951_X_K.E_AI_TNLG.PC_ENT.EU27_2020',
 'Enterprises using AI that generates written/spoken language or programming code, EU27',
 'This is the closest thing to an official generative-AI/LLM adoption statistic anywhere: 1.3% of EU firms in 2021, 2.1% in 2023, then 5.4% in 2024 and 8.8% in 2025 — the ChatGPT inflection visible in national-statistics data.',
 'adoption', 'rate', 'annual', 'official',
 'Percentage of enterprises', NULL, 2, 'dbnomics', 'Eurostat/isoc_eb_ai/A.GE10.C10-S951_X_K.E_AI_TNLG.PC_ENT.EU27_2020',
 'https://db.nomics.world/Eurostat/isoc_eb_ai/A.GE10.C10-S951_X_K.E_AI_TNLG.PC_ENT.EU27_2020',
 NULL, FALSE, FALSE, FALSE, INTERVAL '1 day', NULL),

('dbn.Eurostat.nama_10_lp_a21.A.I15.J.RLPR_HW.EU27_2020',
 'Real labour productivity per hour worked, Information and communication (NACE J), EU27',
 'Thirty years of history in the sector most exposed to AI, so the AI era can be judged against a long pre-AI trend; the dataset also carries 19 NACE activities and 39 countries on the same code pattern for a full productivity-by-industry panel.',
 'adoption', 'index', 'annual', 'official',
 'Index, 2015=100', NULL, 2, 'dbnomics', 'Eurostat/nama_10_lp_a21/A.I15.J.RLPR_HW.EU27_2020',
 'https://db.nomics.world/Eurostat/nama_10_lp_a21/A.I15.J.RLPR_HW.EU27_2020',
 NULL, FALSE, FALSE, FALSE, INTERVAL '1 day', NULL),

('dbn.ONS.PRDY.GYY7.Q',
 'UK output per hour worked, market sector, index 2023=100',
 'The UK''s headline productivity puzzle in one line — 99.3 in 2026-Q1 against 98.3 a year earlier, essentially flat despite the AI investment boom — which is the central empirical question the dashboard exists to track.',
 'adoption', 'index', 'quarterly', 'official',
 'Index, 2023=100, seasonally adjusted (NA-sentinel strings pr', NULL, 2, 'dbnomics', 'ONS/PRDY/GYY7.Q',
 'https://db.nomics.world/ONS/PRDY/GYY7.Q',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'GBR'),

('dbn.Eurostat.isoc_sks_itspt.A.PC_EMP.EU27_2020',
 'Employed ICT specialists as a share of total employment, EU27',
 'Twenty-one years of the AI-relevant labour stock, rising steadily from 3.1% (2004) to 5.0% (2024) — the test of whether AI is substituting for or complementing technical labour is whether this line bends after 2023.',
 'adoption', 'rate', 'annual', 'official',
 'Percentage of total employment', NULL, 2, 'dbnomics', 'Eurostat/isoc_sks_itspt/A.PC_EMP.EU27_2020',
 'https://db.nomics.world/Eurostat/isoc_sks_itspt/A.PC_EMP.EU27_2020',
 NULL, FALSE, FALSE, FALSE, INTERVAL '1 day', NULL),

('dbn.Eurostat.rd_e_berdfundr2.A.TOTAL.G-U_ICT.MIO_EUR.EU27_2020',
 'Business enterprise R&D expenditure in ICT services, EU27',
 'Direct measure of European corporate investment in the sector that builds AI: €8.6bn (2005) to €35.1bn (2023), the input side of the AI economy against which adoption and productivity outputs can be netted.',
 'adoption', 'currency', 'annual', 'official',
 'Million euro', NULL, 2, 'dbnomics', 'Eurostat/rd_e_berdfundr2/A.TOTAL.G-U_ICT.MIO_EUR.EU27_2020',
 'https://db.nomics.world/Eurostat/rd_e_berdfundr2/A.TOTAL.G-U_ICT.MIO_EUR.EU27_2020',
 NULL, FALSE, FALSE, FALSE, INTERVAL '1 day', NULL),

('dbn.Eurostat.jvs_q_nace2.Q.NSA.J.TOTAL.JVR.EU27_2020',
 'Job vacancy rate, Information and communication (NACE J), EU27',
 'The EU mirror of the UK tech-hiring signal — 2.9% in 2024-Q4 falling to 2.2% by 2025-Q3 — letting the dashboard show whether AI-era tech labour demand is contracting on both sides of the Channel.',
 'adoption', 'rate', 'quarterly', 'official',
 'Percent (job vacancy rate), unadjusted', NULL, 2, 'dbnomics', 'Eurostat/jvs_q_nace2/Q.NSA.J.TOTAL.JVR.EU27_2020',
 'https://db.nomics.world/Eurostat/jvs_q_nace2/Q.NSA.J.TOTAL.JVR.EU27_2020',
 NULL, FALSE, FALSE, FALSE, INTERVAL '1 day', NULL),

('dbn.Eurostat.isoc_cicce_use.A.GE10.C10-S951_X_K.E_CC1_PANY.PC_ENT.EU27_202',
 'Enterprises (10+ employees) buying paid cloud computing services, EU27',
 'Cloud is the delivery channel for almost all enterprise AI, so its adoption (40.2% in 2021 to 52.4% in 2025) is the infrastructure precondition that bounds how fast AI use can spread. Caveat: biennial survey, only three observations.',
 'adoption', 'rate', 'annual', 'official',
 'Percentage of enterprises', NULL, 2, 'dbnomics', 'Eurostat/isoc_cicce_use/A.GE10.C10-S951_X_K.E_CC1_PANY.PC_ENT.EU27_2020',
 'https://db.nomics.world/Eurostat/isoc_cicce_use/A.GE10.C10-S951_X_K.E_CC1_PANY.PC_ENT.EU27_2020',
 NULL, FALSE, FALSE, FALSE, INTERVAL '1 day', NULL),

('dbn.Eurostat.nrg_pc_205.S.6000.MWH20000-69999.KWH.X_TAX.EUR.EU27_2020',
 'Electricity price for large industrial consumers (band IE, 20-70 GWh/yr), excluding taxes, EU27',
 'Datacentre economics are electricity economics: this band covers the consumption class most AI datacentres fall into, and its doubling from €0.062/kWh (2007) to €0.166 (2023-S1) before easing to €0.120 (2025-S1) is the cost constraint on European AI compute buildout.',
 'infrastructure', 'currency', 'annual', 'official',
 'Euro per kilowatt-hour, excluding taxes and levies', NULL, 2, 'dbnomics', 'Eurostat/nrg_pc_205/S.6000.MWH20000-69999.KWH.X_TAX.EUR.EU27_2020',
 'https://db.nomics.world/Eurostat/nrg_pc_205/S.6000.MWH20000-69999.KWH.X_TAX.EUR.EU27_2020',
 NULL, FALSE, FALSE, FALSE, INTERVAL '1 day', NULL),

('dbn.Eurostat.nama_10_an6.A.CLV_I15.N117G.EU27_2020',
 'Gross fixed capital formation in intellectual property products, EU27',
 'The national-accounts line that captures software and database capital — the balance-sheet trace of AI investment — sitting at 131.0 (2015=100) in 2024; use asset10=N1132G on the same code pattern for ICT equipment (131.8 in 2024) as the hardware counterpart.',
 'infrastructure', 'index', 'annual', 'official',
 'Chain linked volumes, index 2015=100', NULL, 2, 'dbnomics', 'Eurostat/nama_10_an6/A.CLV_I15.N117G.EU27_2020',
 'https://db.nomics.world/Eurostat/nama_10_an6/A.CLV_I15.N117G.EU27_2020',
 NULL, FALSE, FALSE, FALSE, INTERVAL '1 day', NULL),

('dbn.AMECO.ZVGDF.GBR.3.0.0.0.ZVGDF',
 'Total factor productivity, total economy, United Kingdom',
 'TFP is where an AI-driven general-purpose-technology shock would eventually have to appear, and the UK''s is flat-to-falling (97.2 in 2022 to 96.0 in 2025) — the sharpest available statement of the AI productivity paradox. Caveat: 2025-2027 values are Commission forecasts, not outturns, and should be visually distinguished.',
 'adoption', 'index', 'annual', 'official',
 'Index, 2020=100', NULL, 2, 'dbnomics', 'AMECO/ZVGDF/GBR.3.0.0.0.ZVGDF',
 'https://db.nomics.world/AMECO/ZVGDF/GBR.3.0.0.0.ZVGDF',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'GBR'),

('dbn.Eurostat.isoc_ske_itrcrn2.A.GE10.C10-S951_X_K.E_ITSPVAC2.PC_ENT.EU27_2',
 'Enterprises with hard-to-fill vacancies for ICT specialist roles, EU27',
 'Skills-scarcity gauge: rising 2.8% (2012) to 6.0% (2022) then easing to 5.5% (2024), the first EU data point consistent with AI tools relieving demand for scarce technical labour.',
 'adoption', 'rate', 'annual', 'official',
 'Percentage of enterprises', NULL, 2, 'dbnomics', 'Eurostat/isoc_ske_itrcrn2/A.GE10.C10-S951_X_K.E_ITSPVAC2.PC_ENT.EU27_2020',
 'https://db.nomics.world/Eurostat/isoc_ske_itrcrn2/A.GE10.C10-S951_X_K.E_ITSPVAC2.PC_ENT.EU27_2020',
 NULL, FALSE, FALSE, FALSE, INTERVAL '1 day', NULL),

('dbn.OECD.DSD_ICT_B_DF_BUSINESSES.OECD.A.G14_B.PT_ENT._T.S_GE10',
 'Businesses using artificial intelligence (AI), OECD total, 10+ employees',
 'The only official cross-country measure of firm-level AI adoption: OECD-wide it went 5.6% of firms in 2020 to 20.3% in 2025, which is the single best headline for ''AI is actually being deployed''.',
 'adoption', 'rate', 'annual', 'official',
 'Percentage of enterprises', NULL, 2, 'dbnomics', 'OECD/DSD_ICT_B@DF_BUSINESSES/OECD.A.G14_B.PT_ENT._T.S_GE10',
 'https://db.nomics.world/OECD/DSD_ICT_B@DF_BUSINESSES/OECD.A.G14_B.PT_ENT._T.S_GE10',
 NULL, FALSE, FALSE, FALSE, INTERVAL '1 day', NULL),

('dbn.OECD.DSD_ICT_B_DF_BUSINESSES.OECD.A.G14_B.PT_ENT.J.S_GE10',
 'Businesses using AI — Information and communication sector, OECD, 10+ employees',
 'Shows AI adoption concentrating in the ICT sector first (14.4% in 2020 to 57.5% in 2025), the leading edge that later diffuses to the rest of the economy — the diffusion story in one chart against the all-industry line.',
 'adoption', 'rate', 'annual', 'official',
 'Percentage of enterprises', NULL, 2, 'dbnomics', 'OECD/DSD_ICT_B@DF_BUSINESSES/OECD.A.G14_B.PT_ENT.J.S_GE10',
 'https://db.nomics.world/OECD/DSD_ICT_B@DF_BUSINESSES/OECD.A.G14_B.PT_ENT.J.S_GE10',
 NULL, FALSE, FALSE, FALSE, INTERVAL '1 day', NULL),

('dbn.BEA.NIPA-T50405.LA001282-A',
 'US private fixed investment in data center structures',
 'The most direct dollar measure of the AI capex buildout in existence: $9.2bn in 2020 to $31.1bn in 2024, a 3.4x rise that maps almost one-to-one onto the generative-AI compute boom.',
 'infrastructure', 'currency', 'annual', 'official',
 'Millions of current USD', NULL, 2, 'dbnomics', 'BEA/NIPA-T50405/LA001282-A',
 'https://db.nomics.world/BEA/NIPA-T50405/LA001282-A',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'USA'),

('dbn.WTO.ITS_CS_AX6.000.SI2.000.A',
 'World exports of computer services',
 'Global computer-services exports grew from $120bn in 2005 to $1.077tn in 2024, measuring how much of the world''s software and AI work is now traded across borders — the tradability channel through which AI reallocates work internationally.',
 'infrastructure', 'currency', 'annual', 'official',
 'Millions of current USD', NULL, 2, 'dbnomics', 'WTO/ITS_CS_AX6/000.SI2.000.A',
 'https://db.nomics.world/WTO/ITS_CS_AX6/000.SI2.000.A',
 NULL, FALSE, FALSE, FALSE, INTERVAL '1 day', NULL),

('dbn.BEA.NIPA-T50605.B985RC-A',
 'US private fixed investment in software',
 '66 years of unbroken history ($14m in 1959 to $693bn in 2024) makes this the long-run baseline against which any AI-era acceleration in software capital formation has to be judged.',
 'infrastructure', 'currency', 'annual', 'official',
 'Millions of current USD', NULL, 2, 'dbnomics', 'BEA/NIPA-T50605/B985RC-A',
 'https://db.nomics.world/BEA/NIPA-T50605/B985RC-A',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'USA'),

('dbn.OECD.DSD_PDB_DF_PDB_GR.USA.A.ICTHRS_PCCONLP._T.PD.V.GOY._Z._Z',
 'Contribution of ICT capital deepening to labour productivity growth, United States',
 'Decomposes productivity growth into the part actually caused by ICT capital, so AI investment can be traced to measured output per hour rather than assumed — 38 years of history means the pre-AI baseline is well established. Note it currently ends 2022, so it lags the AI boom by two years.',
 'adoption', 'rate', 'annual', 'official',
 'Percentage points of labour productivity growth', NULL, 2, 'dbnomics', 'OECD/DSD_PDB@DF_PDB_GR/USA.A.ICTHRS_PCCONLP._T.PD.V.GOY._Z._Z',
 'https://db.nomics.world/OECD/DSD_PDB@DF_PDB_GR/USA.A.ICTHRS_PCCONLP._T.PD.V.GOY._Z._Z',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'USA'),

('dbn.ILO.EMP_TEMP_SEX_OCU_NB.USA.BA_453.OCU_ISCO08_4.SEX_T.A',
 'US employment in clerical support workers (ISCO-08 major group 4)',
 'Clerical support is the occupation group every AI-exposure study ranks most automatable, and US employment in it fell from 16.3m in 2003 to 13.6m in 2023 — the displacement hypothesis stated as a directly observable series, on an ISCO basis comparable across 130+ countries.',
 'adoption', 'count', 'annual', 'official',
 'Thousands of persons', NULL, 2, 'dbnomics', 'ILO/EMP_TEMP_SEX_OCU_NB/USA.BA_453.OCU_ISCO08_4.SEX_T.A',
 'https://db.nomics.world/ILO/EMP_TEMP_SEX_OCU_NB/USA.BA_453.OCU_ISCO08_4.SEX_T.A',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'USA'),

('dbn.OECD.DSD_ANBERD_DF_ANBERDi4.USA.A.MA.J62_63.USD_PPP.V.B',
 'US business R&D in computer programming, consultancy and information services (ISIC J62-63)',
 'R&D spending by the exact industry that builds AI systems rose from $16.9bn in 2005 to $79.8bn in 2023, tracking the input side of the AI boom on a PPP-converted basis that is comparable across OECD countries.',
 'adoption', 'currency', 'annual', 'official',
 'Current USD, PPP converted', NULL, 2, 'dbnomics', 'OECD/DSD_ANBERD@DF_ANBERDi4/USA.A.MA.J62_63.USD_PPP.V.B',
 'https://db.nomics.world/OECD/DSD_ANBERD@DF_ANBERDi4/USA.A.MA.J62_63.USD_PPP.V.B',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'USA'),

('dbn.OECD.DSD_ICT_B_DF_BUSINESSES.EU27.A.G14_B.PT_ENT._T.S_GE10',
 'Businesses using artificial intelligence (AI), EU27 total, 10+ employees',
 'The EU27 aggregate (6.0% in 2020 to 19.9% in 2025) is the natural comparison line against the OECD and against individual countries, and it is the series with the widest consistent national coverage underneath it.',
 'adoption', 'rate', 'annual', 'official',
 'Percentage of enterprises', NULL, 2, 'dbnomics', 'OECD/DSD_ICT_B@DF_BUSINESSES/EU27.A.G14_B.PT_ENT._T.S_GE10',
 'https://db.nomics.world/OECD/DSD_ICT_B@DF_BUSINESSES/EU27.A.G14_B.PT_ENT._T.S_GE10',
 NULL, FALSE, FALSE, FALSE, INTERVAL '1 day', NULL),

('dbn.OECD.DSD_PDB_DF_PDB_LV.USA.A.GDPHRS._T.USD_PPP_H.Q._Z._Z._Z',
 'GDP per hour worked, United States, PPP-converted level',
 'PPP-converted productivity levels are the one series that lets you say a country is X dollars per hour behind the US frontier, making it the denominator for every cross-country AI-productivity comparison. Available on the same code pattern for ~50 countries by swapping the country prefix.',
 'adoption', 'currency', 'annual', 'official',
 'US dollars per hour, PPP converted, constant prices', NULL, 2, 'dbnomics', 'OECD/DSD_PDB@DF_PDB_LV/USA.A.GDPHRS._T.USD_PPP_H.Q._Z._Z._Z',
 'https://db.nomics.world/OECD/DSD_PDB@DF_PDB_LV/USA.A.GDPHRS._T.USD_PPP_H.Q._Z._Z._Z',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'USA'),

('dbn.OECD.DSD_VC_DF_VC_INV.USA.VC_INV_MKT.LATER.USD_EXC.A',
 'US later-stage venture capital investment',
 'Late-stage VC is where the large AI rounds land, and the series is current through 2025 ($101.9bn, up from $74.2bn in 2023), giving a near-real-time read on private AI capital that official investment accounts cannot match for timeliness.',
 'effects', 'rate', 'annual', 'official',
 'Millions of USD, exchange rate converted', NULL, 2, 'dbnomics', 'OECD/DSD_VC@DF_VC_INV/USA.VC_INV_MKT.LATER.USD_EXC.A',
 'https://db.nomics.world/OECD/DSD_VC@DF_VC_INV/USA.VC_INV_MKT.LATER.USD_EXC.A',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'USA'),

('dbn.WTO.ITS_CS_AX6.840.SI221.000.A',
 'US exports of cloud computing and data storage services',
 'Cloud is the delivery channel for almost all commercial AI, and US exports of it grew 36x from $230m in 2006 to $8.3bn in 2023 — a clean proxy for AI capability sold abroad as a service.',
 'infrastructure', 'currency', 'annual', 'official',
 'Millions of current USD', NULL, 2, 'dbnomics', 'WTO/ITS_CS_AX6/840.SI221.000.A',
 'https://db.nomics.world/WTO/ITS_CS_AX6/840.SI221.000.A',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'USA'),

('dbn.BEA.NIPA-T50505.B935RC-A',
 'US private fixed investment in computers and peripheral equipment',
 'The hardware counterpart to the data-center series, with 66 years of history: the 2023 dip to $149bn followed by a jump to $178.7bn in 2024 is the GPU buildout showing up in the national accounts.',
 'infrastructure', 'currency', 'annual', 'official',
 'Millions of current USD', NULL, 2, 'dbnomics', 'BEA/NIPA-T50505/B935RC-A',
 'https://db.nomics.world/BEA/NIPA-T50505/B935RC-A',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'USA'),

('dbn.OECD.DSD_ICT_B_DF_BUSINESSES.OECD.A.H1_B.PT_ENT._T.S_GE10',
 'Businesses which employ ICT specialists, OECD total, 10+ employees',
 '13 years of history (2012-2024) on the share of firms employing ICT specialists tests whether AI adoption is accompanied by more in-house technical staff or substitutes for them — the series has stayed flat near 22% while AI adoption quadrupled, which is itself the finding.',
 'adoption', 'rate', 'annual', 'official',
 'Percentage of enterprises', NULL, 2, 'dbnomics', 'OECD/DSD_ICT_B@DF_BUSINESSES/OECD.A.H1_B.PT_ENT._T.S_GE10',
 'https://db.nomics.world/OECD/DSD_ICT_B@DF_BUSINESSES/OECD.A.H1_B.PT_ENT._T.S_GE10',
 NULL, FALSE, FALSE, FALSE, INTERVAL '1 day', NULL),

('dbn.OECD.DSD_PDB_DF_PDB_GR.USA.A.SOFT_PCCONK._T.PD.V.GOY._Z._Z',
 'Contribution of computer software and databases to total capital growth, United States',
 'Software''s share of US capital growth rose steadily to 1.49 percentage points by 2022, isolating the intangible-capital channel through which AI shows up as accumulated capital rather than as labour. Ends 2022, so it trails the AI boom.',
 'infrastructure', 'rate', 'annual', 'official',
 'Percentage points of total capital growth', NULL, 2, 'dbnomics', 'OECD/DSD_PDB@DF_PDB_GR/USA.A.SOFT_PCCONK._T.PD.V.GOY._Z._Z',
 'https://db.nomics.world/OECD/DSD_PDB@DF_PDB_GR/USA.A.SOFT_PCCONK._T.PD.V.GOY._Z._Z',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'USA'),

('dbn.NBS.A_A0E0H.A0E0H28',
 'China — Output of Integrated Circuits (annual)',
 'China fabricates and packages a large share of the world''s chips, so its IC unit output is the most direct national-scale measure of the physical AI-hardware buildout; output grew 3.7x from 131.8bn units (2016) to 484.3bn units (2025), with the steepest jump landing in the 2023-2025 AI capex wave.',
 'infrastructure', 'currency', 'annual', 'official',
 '10,000 pieces (dimension unit=10000_pieces); 2025 value 48,4', NULL, 2, 'dbnomics', 'NBS/A_A0E0H/A0E0H28',
 'https://db.nomics.world/NBS/A_A0E0H/A0E0H28',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'CHN'),

('dbn.NBS.A_A0711.A071107',
 'China — Output of Energy Products: Electricity (annual)',
 'AI compute is electricity-constrained, and China''s total generation sets the hard ceiling on how much domestic AI training and inference capacity can physically run; observed 61,331.6 (2016) to 105,752.5 (2025) hundred-million kWh, i.e. 6.13 to 10.58 petawatt-hours.',
 'infrastructure', 'currency', 'annual', 'official',
 '100 million kWh (dimension unit=100_million_kwh)', NULL, 2, 'dbnomics', 'NBS/A_A0711/A071107',
 'https://db.nomics.world/NBS/A_A0711/A071107',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'CHN'),

('dbn.STATJP.MIm.M.EP.B.TTP.SA',
 'Japan — Employed Persons, both sexes, seasonally adjusted (monthly)',
 'Japan is the AI-exposed advanced economy with the tightest labour market, so a 73-year monthly employment series is the cleanest baseline for detecting whether AI adoption bends aggregate employment; the deepest and most current series found anywhere in this assignment (882 observations, current to June 2026).',
 'adoption', 'currency', 'monthly', 'official',
 'ten thousand persons (2026-06 value 6,846 = 68.46 million em', NULL, 2, 'dbnomics', 'STATJP/MIm/M.EP.B.TTP.SA',
 'https://db.nomics.world/STATJP/MIm/M.EP.B.TTP.SA',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'JPN'),

('dbn.RBA.H4.GNFPROSQI',
 'Australia — Non-farm labour productivity per hour (quarterly)',
 'Labour productivity per hour is the headline variable any AI-impact dashboard must show, and this gives a 40-year advanced-economy series current to 2026-Q1 — long enough to establish the pre-AI trend that any AI-era acceleration would have to beat.',
 'adoption', 'index', 'quarterly', 'official',
 'index (observed base period 2025-Q4 = 100.0; 1985-Q3 = 65.9)', NULL, 2, 'dbnomics', 'RBA/H4/GNFPROSQI',
 'https://db.nomics.world/RBA/H4/GNFPROSQI',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'AUS'),

('dbn.RBA.H5.GLFOSVTLF',
 'Australia — Vacancies to labour force ratio (quarterly)',
 'Job-vacancy intensity is the leading indicator that turns first if AI substitutes for hiring rather than for incumbent workers; a 47-year series lets you separate the AI-era decline from ordinary cyclical softening, and it is current to May 2026.',
 'adoption', 'rate', 'monthly', 'official',
 'ratio, percent of labour force (2026-05 value 2.137)', NULL, 2, 'dbnomics', 'RBA/H5/GLFOSVTLF',
 'https://db.nomics.world/RBA/H5/GLFOSVTLF',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'AUS'),

('dbn.NBS.A_A0G11.A0G1101',
 'China — Software Income (Main Indicators on Software and IT Services, annual)',
 'Total revenue of China''s software and IT services industry is the revenue-side counterpart to its chip output, showing whether AI is translating into monetised software value; it tripled from 4.82trn yuan (2016) to 15.48trn yuan (2025).',
 'infrastructure', 'magnitude', 'annual', 'official',
 '10,000 yuan (dimension unit=10000_yuan); 2025 value 1,548,31', NULL, 2, 'dbnomics', 'NBS/A_A0G11/A0G1101',
 'https://db.nomics.world/NBS/A_A0G11/A0G1101',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'CHN'),

('dbn.NBS.A_A0406.A040608',
 'China — Employed Persons in Urban Units: Information Transmission, Software and IT Services (annual)',
 'This is the direct Chinese analogue of the US information-sector employment series (USINFO) the project already holds, enabling a like-for-like US-vs-China comparison of whether AI is growing or shrinking headcount in the sector that builds it; 3.64m (2016) to 5.53m (2024).',
 'adoption', 'currency', 'annual', 'official',
 '10,000 persons (dimension unit=10000_persons); 2024 value 55', NULL, 2, 'dbnomics', 'NBS/A_A0406/A040608',
 'https://db.nomics.world/NBS/A_A0406/A040608',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'CHN'),

('dbn.NBS.A_A040I.A040I08',
 'China — Average Wage in Urban Units: Information Transmission, Computer Service and Software (annual)',
 'The AI skills premium shows up as a widening wage gap between the ICT sector and manufacturing; pair with NBS/A_A040I/A040I04 (manufacturing wage, same dataset, verified 2016-2024) to chart the ratio, which moved from 2.06x (2016) to 2.21x (2024).',
 'adoption', 'magnitude', 'annual', 'official',
 'yuan per year (2024 value 238,966 yuan; manufacturing compar', NULL, 2, 'dbnomics', 'NBS/A_A040I/A040I08',
 'https://db.nomics.world/NBS/A_A040I/A040I08',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'CHN'),

('dbn.BOJ.SPPI.5201450003',
 'Japan — Services Producer Price Index: Internet data centers (monthly)',
 'A genuine transaction-price index for data-centre services — rare anywhere in official statistics and the single most AI-specific price series found in this assignment; it shows Japanese data-centre prices falling below the 2015 base through 2023 and then turning up to 100.1 by April 2024, the moment AI demand started absorbing capacity. Caveat: the DBnomics BOJ mirror stopped updating at 2024-04.',
 'infrastructure', 'index', 'monthly', 'official',
 'index, 2015 = 100 (2015-01 = 100.0; 2024-04 = 100.1)', NULL, 2, 'dbnomics', 'BOJ/SPPI/5201450003',
 'https://db.nomics.world/BOJ/SPPI/5201450003',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'JPN'),

('dbn.BOJ.SPPI.5201350004',
 'Japan — Services Producer Price Index: Entrusted computing services, Cloud application (monthly)',
 'A dedicated cloud-application price index — the price of the compute layer AI is sold through; it declined steadily to 95.0 by April 2024 against a 2015 base of 100.8, evidence that cloud unit prices kept deflating even as AI demand rose. Caveat: DBnomics BOJ mirror ends 2024-04.',
 'infrastructure', 'index', 'monthly', 'official',
 'index, 2015 = 100 (2015-01 = 100.8; 2024-04 = 95.0)', NULL, 2, 'dbnomics', 'BOJ/SPPI/5201350004',
 'https://db.nomics.world/BOJ/SPPI/5201350004',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'JPN'),

('dbn.BOJ.SPPI.5201330001',
 'Japan — Services Producer Price Index: Software development (monthly)',
 'If AI coding tools are cutting the cost of producing software, the software-development price index is where it must eventually appear; instead it rose from 99.9 (2015) to 114.0 (April 2024), so the series is a direct test — currently negative — of the cheap-software thesis. Caveat: DBnomics BOJ mirror ends 2024-04.',
 'infrastructure', 'index', 'monthly', 'official',
 'index, 2015 = 100 (2015-01 = 99.9; 2024-04 = 114.0)', NULL, 2, 'dbnomics', 'BOJ/SPPI/5201330001',
 'https://db.nomics.world/BOJ/SPPI/5201330001',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'JPN'),

('dbn.JILPT.e0208.M.1.1',
 'Japan — Active job openings-to-applicants ratio, excl. new graduates, incl. part-timers (monthly)',
 'Japan''s canonical labour-tightness gauge (yukokyujinbairitsu): openings per applicant, so a fall below trend is the first visible sign of AI reducing hiring demand; it softened from 1.23 (March 2022) to 1.18 (June 2026) and is current to last month.',
 'adoption', 'magnitude', 'monthly', 'official',
 'ratio, job openings per applicant (2026-06 = 1.18)', NULL, 2, 'dbnomics', 'JILPT/e0208/M.1.1',
 'https://db.nomics.world/JILPT/e0208/M.1.1',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'JPN'),

('dbn.RBA.H4.GNFULCYP',
 'Australia — Year-ended non-farm unit labour costs growth (quarterly)',
 'Unit labour costs are the pass-through channel from AI-driven productivity to prices, and this mirrors the US unit-labour-cost series already held; growth decelerated from 5.17% (2025-Q3) to 3.22% (2026-Q1), the pattern you would expect if productivity were picking up.',
 'adoption', 'rate', 'quarterly', 'official',
 'percent, year-ended growth (2026-Q1 = 3.22%)', NULL, 2, 'dbnomics', 'RBA/H4/GNFULCYP',
 'https://db.nomics.world/RBA/H4/GNFULCYP',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'AUS'),

('dbn.BOJ.CGPI.2300440015',
 'Japan — Export Price Index (contract currency): Semiconductor making equipment (monthly)',
 'Japan supplies a critical share of world semiconductor manufacturing equipment, so the export price of that equipment is a pricing-power read on the AI fab buildout; it rose from 100.3 (2020) to 112.9 (May 2024). Caveat: only 53 observations and the DBnomics BOJ mirror ends 2024-05.',
 'infrastructure', 'index', 'monthly', 'official',
 'index, 2020 = 100 (2020-01 = 100.3; 2024-05 = 112.9)', NULL, 2, 'dbnomics', 'BOJ/CGPI/2300440015',
 'https://db.nomics.world/BOJ/CGPI/2300440015',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'JPN'),

('dbn.NBS.M_A02092Q.A02092Q01',
 'China — Output of Integrated Circuits, Current Period (monthly)',
 'The highest-frequency read on China''s chip production anywhere in this provider set, showing output climbing from 36.3bn units (March 2025) to 48.1bn (December 2025). IMPORTANT CAVEAT: DBnomics mirrors the NBS rolling window, so this returns only a 13-month span (2025-02 to 2026-02) of which just 10 points are non-null — the adapter must snapshot each month and accumulate its own history, or the ',
 'infrastructure', 'currency', 'monthly', 'official',
 '100 million units (dimension unit=100_million_units); 2025-1', NULL, 2, 'dbnomics', 'NBS/M_A02092Q/A02092Q01',
 'https://db.nomics.world/NBS/M_A02092Q/A02092Q01',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'CHN'),

('fred.PCU518210518210',
 'PPI by Industry: Data Processing, Hosting and Related Services',
 'The direct price of renting compute — this is the closest thing the US statistical system has to an ''AI cloud price index'', so it shows whether the AI buildout is deflating or inflating the cost of the compute layer everything else runs on.',
 'infrastructure', 'index', 'monthly', 'official',
 'Index Dec 2000=100', NULL, 2, 'fred', 'PCU518210518210',
 'https://fred.stlouisfed.org/series/PCU518210518210',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'USA'),

('fred.A679RC1Q027SBEA',
 'Private Fixed Investment in Information Processing Equipment and Software',
 'The single best national-accounts measure of the AI capex boom: servers, GPUs and software bought by US business, running $1.61tn annualised in 2026Q2 against $1.47tn three quarters earlier.',
 'infrastructure', 'currency', 'quarterly', 'official',
 'Billions of Dollars', NULL, 2, 'fred', 'A679RC1Q027SBEA',
 'https://fred.stlouisfed.org/series/A679RC1Q027SBEA',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'USA'),

('dbn.EIA.ELEC.GEN.ALL-US-99.M',
 'Electricity Net Generation, All Sectors, United States',
 'AI''s physical constraint is power; total US net generation is the supply side of the data-centre energy story and the denominator for every ''what share does AI consume'' claim.',
 'infrastructure', 'magnitude', 'monthly', 'official',
 'Thousand megawatthours', NULL, 2, 'dbnomics', 'EIA/ELEC/GEN.ALL-US-99.M',
 'https://db.nomics.world/EIA/ELEC/GEN.ALL-US-99.M',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'USA'),

('dbn.EIA.ELEC.SALES.US-COM.M',
 'Retail Sales of Electricity, Commercial Sector, United States',
 'Data centres are classified commercial, not industrial, in EIA''s accounts — so this series is where the AI load actually shows up, and it has risen 32% since 2001 while industrial sales were flat.',
 'infrastructure', 'currency', 'monthly', 'official',
 'Million kilowatthours', NULL, 2, 'dbnomics', 'EIA/ELEC/SALES.US-COM.M',
 'https://db.nomics.world/EIA/ELEC/SALES.US-COM.M',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'USA'),

('dbn.EIA.ELEC.PRICE.US-IND.M',
 'Average Retail Price of Electricity, Industrial Sector, United States',
 'Industrial electricity prices are the input cost that decides where AI compute gets built; the series has gone 4.73 to 8.58 cents/kWh since 2001, most of it recent.',
 'infrastructure', 'magnitude', 'monthly', 'official',
 'Cents per kilowatthour', NULL, 2, 'dbnomics', 'EIA/ELEC/PRICE.US-IND.M',
 'https://db.nomics.world/EIA/ELEC/PRICE.US-IND.M',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'USA'),

('fred.PCU334413334413',
 'PPI by Industry: Semiconductor and Related Device Manufacturing',
 'Semiconductor prices are the cost floor under all AI compute; the index has fallen from 100 (Dec 1998) to 28.99, quantifying nearly three decades of quality-adjusted chip deflation.',
 'infrastructure', 'index', 'monthly', 'official',
 'Index Dec 1998=100', NULL, 2, 'fred', 'PCU334413334413',
 'https://fred.stlouisfed.org/series/PCU334413334413',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'USA'),

('fred.RVAI',
 'Real Value Added by Industry: Information',
 'Sector-level output for the tech industries themselves — the ''tech'' half of a tech vs non-tech comparison, and the cleanest test of whether AI is showing up as measured output rather than just investment.',
 'effects', 'currency', 'quarterly', 'official',
 'Billions of Chained 2017 Dollars', NULL, 2, 'fred', 'RVAI',
 'https://fred.stlouisfed.org/series/RVAI',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'USA'),

('fred.RVASPI',
 'Real Value Added by Industry: Private Services-Producing Industries',
 'The non-tech comparator that makes RVAI interpretable: Information grew 3.1% in 2026Q1 against 0.2% for private services as a whole, which is the AI-concentration story in two numbers.',
 'effects', 'currency', 'quarterly', 'official',
 'Billions of Chained 2017 Dollars', NULL, 2, 'fred', 'RVASPI',
 'https://fred.stlouisfed.org/series/RVASPI',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'USA'),

('fred.PCU333242333242',
 'PPI by Industry: Semiconductor Machinery Manufacturing',
 'The cost of the lithography and fab tooling that has to be bought before any AI chip exists — an upstream leading indicator of semiconductor capacity expansion.',
 'infrastructure', 'index', 'monthly', 'official',
 'Index Dec 2003=100', NULL, 2, 'fred', 'PCU333242333242',
 'https://fred.stlouisfed.org/series/PCU333242333242',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'USA'),

('dbn.Eurostat.nrg_pc_205.S.6000.MWH_GE150000.KWH.X_TAX.EUR.EU27_2020',
 'Electricity Prices for Non-Household Consumers, Band IG (150,000 MWh and over), EU27, Excluding Taxes',
 'The very-large-consumer band is the data-centre tariff band; EU prices have gone 0.0381 to 0.1022 EUR/kWh since 2007, which is the European counterweight to the US industrial price series and explains siting decisions.',
 'infrastructure', 'currency', 'annual', 'official',
 'EUR per kilowatt-hour, excluding taxes and levies', NULL, 2, 'dbnomics', 'Eurostat/nrg_pc_205/S.6000.MWH_GE150000.KWH.X_TAX.EUR.EU27_2020',
 'https://db.nomics.world/Eurostat/nrg_pc_205/S.6000.MWH_GE150000.KWH.X_TAX.EUR.EU27_2020',
 NULL, FALSE, FALSE, FALSE, INTERVAL '1 day', NULL),

('fred.IPG334S',
 'Industrial Production: Computer and Electronic Product Manufacturing',
 'Physical output volume for the whole computer-and-electronics sector, the broader companion to the semiconductor-only IPG3344S already held, and up 140.6 vs a 2017 base.',
 'infrastructure', 'index', 'monthly', 'official',
 'Index 2017=100', NULL, 2, 'fred', 'IPG334S',
 'https://fred.stlouisfed.org/series/IPG334S',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'USA'),

('fred.IQ12260',
 'Export Price Index (End Use): Nonmonetary Gold',
 'This is the working answer to the gold question: FRED''s LBMA gold price series were withdrawn, and this BLS index is the only gold price series still live on FRED, tracking gold up 54.8% since Dec 2024 as a macro-uncertainty gauge alongside the AI capex cycle.',
 'infrastructure', 'index', 'monthly', 'official',
 'Index Dec 2024=100', NULL, 2, 'fred', 'IQ12260',
 'https://fred.stlouisfed.org/series/IQ12260',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'USA'),

('dbn.IMF.PCPS.M.W00.PGOLD.USD',
 'Primary Commodity Prices: Gold, US Dollars',
 'Gold in actual dollars per troy ounce rather than index form ($409.82 in Jan 1990 to $3,351.86 in Jun 2025) — use it for the level and history, but see the staleness warning in notes.',
 'infrastructure', 'currency', 'monthly', 'official',
 'US Dollars per troy ounce', NULL, 2, 'dbnomics', 'IMF/PCPS/M.W00.PGOLD.USD',
 'https://db.nomics.world/IMF/PCPS/M.W00.PGOLD.USD',
 NULL, FALSE, FALSE, FALSE, INTERVAL '1 day', NULL),

('fred.TLMFGCONS',
 'Total Construction Spending: Manufacturing in the United States',
 'Captures the physical fab-building boom — CHIPS Act and AI-driven semiconductor plant construction — running $172.7bn annualised in Jun 2026 versus roughly $70bn pre-2021.',
 'infrastructure', 'rate', 'monthly', 'official',
 'Millions of Dollars, seasonally adjusted annual rate', NULL, 2, 'fred', 'TLMFGCONS',
 'https://fred.stlouisfed.org/series/TLMFGCONS',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'USA'),

('fred.B985RC1Q027SBEA',
 'Private Fixed Investment: Nonresidential: Intellectual Property Products: Software',
 'Isolates the software half of AI capex from the hardware half, so you can show whether the boom is chips-led or code-led — $814.5bn annualised in 2026Q2.',
 'infrastructure', 'currency', 'quarterly', 'official',
 'Billions of Dollars', NULL, 2, 'fred', 'B985RC1Q027SBEA',
 'https://fred.stlouisfed.org/series/B985RC1Q027SBEA',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'USA'),

('dbn.EIA.ELEC.SALES.US-IND.M',
 'Retail Sales of Electricity, Industrial Sector, United States',
 'The flat-line control against which commercial (data-centre) electricity growth reads as a genuine AI signal rather than economy-wide electrification: 83,477 GWh in Jan 2001 against 85,228 GWh in Mar 2026.',
 'infrastructure', 'currency', 'monthly', 'official',
 'Million kilowatthours', NULL, 2, 'dbnomics', 'EIA/ELEC/SALES.US-IND.M',
 'https://db.nomics.world/EIA/ELEC/SALES.US-IND.M',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'USA'),

('fred.A34SNO',
 'Manufacturers'' New Orders: Computers and Electronic Products',
 'A forward-looking monthly order book for AI hardware demand, faster to move than the quarterly BEA investment series.',
 'effects', 'currency', 'monthly', 'official',
 'Millions of Dollars', NULL, 2, 'fred', 'A34SNO',
 'https://fred.stlouisfed.org/series/A34SNO',
 NULL, TRUE, FALSE, FALSE, INTERVAL '1 day', 'USA')

ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description,
  pillar = EXCLUDED.pillar, unit = EXCLUDED.unit,
  source_series_code = EXCLUDED.source_series_code,
  source_url = EXCLUDED.source_url,
  default_country_iso3 = EXCLUDED.default_country_iso3,
  updated_at = now();
