-- ============================================================================
-- 027_financing_events.sql — the AI circular-financing deal graph
--
-- GENERATED by scripts/load-financing-deals.js from the research table and the
-- editorial decisions in docs/financing/decisions.json. Do not hand-edit;
-- change the decisions file and re-run the script.
--
-- WHAT THESE ARE
--
-- 23 dated financing transactions between AI labs, chipmakers, hyperscalers,
-- GPU clouds, data-centre operators, private credit and sovereign funds, each
-- with a source URL that resolved when the loader last checked.
--
-- 33 rows went in. 9 were rejected and 1 was merged into an
-- earlier event as a completion rather than loaded as a second deal. Every
-- rejection and its reason is in docs/financing/deals.json.
--
-- NOTHING HERE HAS BEEN VERIFIED BY A PERSON. Every row lands with
-- is_verified = FALSE and event_citations.is_checked = FALSE, regardless of what
-- the research called "confirmed" — that word described the source's own
-- confidence, not ours. `SELECT * FROM unverified_loops` is the worklist.
--
-- READ THE AMOUNTS WITH amount_basis. A commitment is a ceiling and a
-- disclosed_total is a transaction; summing them together produces a number
-- describing nothing. The same goes for direction: a stake in a lab and the
-- cloud order tied to it are two rows pointing opposite ways, and that is the
-- finding rather than a bug.
-- ============================================================================

-- row  1 · Microsoft → OpenAI Global LLC
-- equity investment
WITH upserted AS (
  INSERT INTO events (
    kind, status, from_entity_id, to_entity_id,
    amount_usd, amount_basis, amount_is_estimate,
    announced_date, completed_date, location_iso3,
    headline, confidence_tier, is_verified, dedup_hash,
    loop_status, loop_description, structure_label, is_bidirectional
  ) VALUES (
    'investment', 'announced', 'microsoft', 'openai',
    13000000000, 'commitment', FALSE,
    '2025-09-30', NULL, NULL,
    'Microsoft → OpenAI: equity investment ($13bn commitment)', 'official', FALSE, 'bc68096e463cc478bb736f6df980d929795e52c92bfb1938bb8493dc06648478',
    'forms_loop', 'Microsoft commits $13B to OpenAI accounted under equity method while also being exclusive cloud provider', 'equity investment', FALSE
  )
  ON CONFLICT (dedup_hash) DO UPDATE SET
    kind = EXCLUDED.kind, status = EXCLUDED.status,
    from_entity_id = EXCLUDED.from_entity_id, to_entity_id = EXCLUDED.to_entity_id,
    amount_usd = EXCLUDED.amount_usd, amount_basis = EXCLUDED.amount_basis,
    announced_date = EXCLUDED.announced_date, completed_date = EXCLUDED.completed_date,
    location_iso3 = EXCLUDED.location_iso3, headline = EXCLUDED.headline,
    confidence_tier = EXCLUDED.confidence_tier,
    loop_status = EXCLUDED.loop_status, loop_description = EXCLUDED.loop_description,
    structure_label = EXCLUDED.structure_label,
    is_bidirectional = EXCLUDED.is_bidirectional,
    updated_at = now()
  RETURNING id
)
INSERT INTO event_citations (event_id, url, publisher, publisher_class, is_primary, http_status, fetched_at, note)
SELECT id, 'https://microsoft.gcs-web.com/static-files/b0a66351-38cf-4147-a907-191d774531bb', 'microsoft.gcs-web.com', 'filing',
       TRUE,
       200, '2026-08-30T02:35:06.388Z'::timestamptz, NULL
  FROM upserted
ON CONFLICT (event_id, url) DO UPDATE SET
  publisher = EXCLUDED.publisher, publisher_class = EXCLUDED.publisher_class,
  is_primary = EXCLUDED.is_primary,
  http_status = EXCLUDED.http_status, fetched_at = EXCLUDED.fetched_at,
  note = EXCLUDED.note;

-- row  2 · OpenAI PBC → Microsoft Azure
-- cloud services purchase commitment
WITH upserted AS (
  INSERT INTO events (
    kind, status, from_entity_id, to_entity_id,
    amount_usd, amount_basis, amount_is_estimate,
    announced_date, completed_date, location_iso3,
    headline, confidence_tier, is_verified, dedup_hash,
    loop_status, loop_description, structure_label, is_bidirectional
  ) VALUES (
    'offtake', 'announced', 'openai', 'microsoft',
    250000000000, 'commitment', FALSE,
    '2025-10-28', NULL, NULL,
    'OpenAI → Microsoft: cloud services purchase commitment ($250bn commitment)', 'official', FALSE, '257c244b3408719cc128a6b7911185cda58522dc0ea3434758d820294f179a34',
    'forms_loop', 'OpenAI contracts to buy $250B of Azure services under new partnership agreement', 'cloud services purchase commitment', FALSE
  )
  ON CONFLICT (dedup_hash) DO UPDATE SET
    kind = EXCLUDED.kind, status = EXCLUDED.status,
    from_entity_id = EXCLUDED.from_entity_id, to_entity_id = EXCLUDED.to_entity_id,
    amount_usd = EXCLUDED.amount_usd, amount_basis = EXCLUDED.amount_basis,
    announced_date = EXCLUDED.announced_date, completed_date = EXCLUDED.completed_date,
    location_iso3 = EXCLUDED.location_iso3, headline = EXCLUDED.headline,
    confidence_tier = EXCLUDED.confidence_tier,
    loop_status = EXCLUDED.loop_status, loop_description = EXCLUDED.loop_description,
    structure_label = EXCLUDED.structure_label,
    is_bidirectional = EXCLUDED.is_bidirectional,
    updated_at = now()
  RETURNING id
)
INSERT INTO event_citations (event_id, url, publisher, publisher_class, is_primary, http_status, fetched_at, note)
SELECT id, 'https://www.sec.gov/Archives/edgar/data/789019/000119312525256321/R26.htm', 'sec.gov', 'filing',
       TRUE,
       200, '2026-08-30T02:35:06.467Z'::timestamptz, NULL
  FROM upserted
ON CONFLICT (event_id, url) DO UPDATE SET
  publisher = EXCLUDED.publisher, publisher_class = EXCLUDED.publisher_class,
  is_primary = EXCLUDED.is_primary,
  http_status = EXCLUDED.http_status, fetched_at = EXCLUDED.fetched_at,
  note = EXCLUDED.note;

-- row  3 · Amazon → Anthropic PBC
-- equity investment + strategic collaboration
WITH upserted AS (
  INSERT INTO events (
    kind, status, from_entity_id, to_entity_id,
    amount_usd, amount_basis, amount_is_estimate,
    announced_date, completed_date, location_iso3,
    headline, confidence_tier, is_verified, dedup_hash,
    loop_status, loop_description, structure_label, is_bidirectional
  ) VALUES (
    'investment', 'announced', 'amazon', 'anthropic',
    4000000000, 'commitment', FALSE,
    '2023-09-24', NULL, NULL,
    'Amazon → Anthropic: equity investment + strategic collaboration ($4bn commitment)', 'official', FALSE, '9bcaf9610ef47ff056247f6239ee89cd989999af1327c13bc30d02186dfe646c',
    'forms_loop', 'Amazon invests up to $4B in Anthropic and Anthropic commits to use AWS as primary cloud and Trainium chips', 'equity investment + strategic collaboration', FALSE
  )
  ON CONFLICT (dedup_hash) DO UPDATE SET
    kind = EXCLUDED.kind, status = EXCLUDED.status,
    from_entity_id = EXCLUDED.from_entity_id, to_entity_id = EXCLUDED.to_entity_id,
    amount_usd = EXCLUDED.amount_usd, amount_basis = EXCLUDED.amount_basis,
    announced_date = EXCLUDED.announced_date, completed_date = EXCLUDED.completed_date,
    location_iso3 = EXCLUDED.location_iso3, headline = EXCLUDED.headline,
    confidence_tier = EXCLUDED.confidence_tier,
    loop_status = EXCLUDED.loop_status, loop_description = EXCLUDED.loop_description,
    structure_label = EXCLUDED.structure_label,
    is_bidirectional = EXCLUDED.is_bidirectional,
    updated_at = now()
  RETURNING id
)
INSERT INTO event_citations (event_id, url, publisher, publisher_class, is_primary, http_status, fetched_at, note)
SELECT id, 'https://press.aboutamazon.com/2023/9/amazon-and-anthropic-announce-strategic-collaboration-to-advance-generative-ai', 'press.aboutamazon.com', 'company_release',
       TRUE,
       200, '2026-08-30T02:35:06.547Z'::timestamptz, NULL
  FROM upserted
ON CONFLICT (event_id, url) DO UPDATE SET
  publisher = EXCLUDED.publisher, publisher_class = EXCLUDED.publisher_class,
  is_primary = EXCLUDED.is_primary,
  http_status = EXCLUDED.http_status, fetched_at = EXCLUDED.fetched_at,
  note = EXCLUDED.note;

-- row  4 · Anthropic PBC → AWS
-- committed use cloud contract
WITH upserted AS (
  INSERT INTO events (
    kind, status, from_entity_id, to_entity_id,
    amount_usd, amount_basis, amount_is_estimate,
    announced_date, completed_date, location_iso3,
    headline, confidence_tier, is_verified, dedup_hash,
    loop_status, loop_description, structure_label, is_bidirectional
  ) VALUES (
    'offtake', 'announced', 'anthropic', 'amazon',
    4000000000, 'commitment', FALSE,
    '2023-09-24', NULL, NULL,
    'Anthropic → Amazon: committed use cloud contract ($4bn commitment)', 'news_derived', FALSE, '2e207b18b28e0f85ef671e6675ae63ac85a6673dc959f119d1a229d1e0feb4a6',
    'forms_loop', 'Anthropic’s committed use contract requires $4B AWS spend over five years linked to Amazon’s investment', 'committed use cloud contract', FALSE
  )
  ON CONFLICT (dedup_hash) DO UPDATE SET
    kind = EXCLUDED.kind, status = EXCLUDED.status,
    from_entity_id = EXCLUDED.from_entity_id, to_entity_id = EXCLUDED.to_entity_id,
    amount_usd = EXCLUDED.amount_usd, amount_basis = EXCLUDED.amount_basis,
    announced_date = EXCLUDED.announced_date, completed_date = EXCLUDED.completed_date,
    location_iso3 = EXCLUDED.location_iso3, headline = EXCLUDED.headline,
    confidence_tier = EXCLUDED.confidence_tier,
    loop_status = EXCLUDED.loop_status, loop_description = EXCLUDED.loop_description,
    structure_label = EXCLUDED.structure_label,
    is_bidirectional = EXCLUDED.is_bidirectional,
    updated_at = now()
  RETURNING id
)
INSERT INTO event_citations (event_id, url, publisher, publisher_class, is_primary, http_status, fetched_at, note)
SELECT id, 'https://www.ftc.gov/system/files/ftc_gov/pdf/p246201_aipartnerships6breport_redacted_0.pdf', 'ftc.gov', 'regulator',
       TRUE,
       200, '2026-08-30T02:35:06.636Z'::timestamptz, NULL
  FROM upserted
ON CONFLICT (event_id, url) DO UPDATE SET
  publisher = EXCLUDED.publisher, publisher_class = EXCLUDED.publisher_class,
  is_primary = EXCLUDED.is_primary,
  http_status = EXCLUDED.http_status, fetched_at = EXCLUDED.fetched_at,
  note = EXCLUDED.note;

-- row  6 · Amazon → Anthropic PBC
-- additional equity investment
WITH upserted AS (
  INSERT INTO events (
    kind, status, from_entity_id, to_entity_id,
    amount_usd, amount_basis, amount_is_estimate,
    announced_date, completed_date, location_iso3,
    headline, confidence_tier, is_verified, dedup_hash,
    loop_status, loop_description, structure_label, is_bidirectional
  ) VALUES (
    'investment', 'announced', 'amazon', 'anthropic',
    4000000000, 'commitment', FALSE,
    '2024-11-21', NULL, NULL,
    'Amazon → Anthropic: additional equity investment ($4bn commitment)', 'official', FALSE, '6826eb307eb3a0f881b0ae91cb0358f98ce9a1e1e1f89a7620a86d2f00a9e3ba',
    'forms_loop', 'Amazon announces additional $4B Anthropic investment raising cumulative to $8B', 'additional equity investment', FALSE
  )
  ON CONFLICT (dedup_hash) DO UPDATE SET
    kind = EXCLUDED.kind, status = EXCLUDED.status,
    from_entity_id = EXCLUDED.from_entity_id, to_entity_id = EXCLUDED.to_entity_id,
    amount_usd = EXCLUDED.amount_usd, amount_basis = EXCLUDED.amount_basis,
    announced_date = EXCLUDED.announced_date, completed_date = EXCLUDED.completed_date,
    location_iso3 = EXCLUDED.location_iso3, headline = EXCLUDED.headline,
    confidence_tier = EXCLUDED.confidence_tier,
    loop_status = EXCLUDED.loop_status, loop_description = EXCLUDED.loop_description,
    structure_label = EXCLUDED.structure_label,
    is_bidirectional = EXCLUDED.is_bidirectional,
    updated_at = now()
  RETURNING id
)
INSERT INTO event_citations (event_id, url, publisher, publisher_class, is_primary, http_status, fetched_at, note)
SELECT id, 'https://www.aboutamazon.com/news/aws/amazon-invests-additional-4-billion-anthropic-ai', 'aboutamazon.com', 'company_release',
       TRUE,
       200, '2026-08-30T02:35:07.569Z'::timestamptz, NULL
  FROM upserted
ON CONFLICT (event_id, url) DO UPDATE SET
  publisher = EXCLUDED.publisher, publisher_class = EXCLUDED.publisher_class,
  is_primary = EXCLUDED.is_primary,
  http_status = EXCLUDED.http_status, fetched_at = EXCLUDED.fetched_at,
  note = EXCLUDED.note;

-- row  7 · Amazon → Anthropic PBC
-- equity investment + milestone commitments
WITH upserted AS (
  INSERT INTO events (
    kind, status, from_entity_id, to_entity_id,
    amount_usd, amount_basis, amount_is_estimate,
    announced_date, completed_date, location_iso3,
    headline, confidence_tier, is_verified, dedup_hash,
    loop_status, loop_description, structure_label, is_bidirectional
  ) VALUES (
    'investment', 'announced', 'amazon', 'anthropic',
    5000000000, 'commitment', FALSE,
    '2026-04-20', NULL, NULL,
    'Amazon → Anthropic: equity investment + milestone commitments ($5bn commitment)', 'news_derived', FALSE, 'b39d71a13e85b72dab2710b3ac0f9e53ec11dce8128f9504bab8b464d2d5bedf',
    'forms_loop', 'Amazon injects $5B and commits up to $20B more while Anthropic agrees to $100B AWS spend over 10 years', 'equity investment + milestone commitments', FALSE
  )
  ON CONFLICT (dedup_hash) DO UPDATE SET
    kind = EXCLUDED.kind, status = EXCLUDED.status,
    from_entity_id = EXCLUDED.from_entity_id, to_entity_id = EXCLUDED.to_entity_id,
    amount_usd = EXCLUDED.amount_usd, amount_basis = EXCLUDED.amount_basis,
    announced_date = EXCLUDED.announced_date, completed_date = EXCLUDED.completed_date,
    location_iso3 = EXCLUDED.location_iso3, headline = EXCLUDED.headline,
    confidence_tier = EXCLUDED.confidence_tier,
    loop_status = EXCLUDED.loop_status, loop_description = EXCLUDED.loop_description,
    structure_label = EXCLUDED.structure_label,
    is_bidirectional = EXCLUDED.is_bidirectional,
    updated_at = now()
  RETURNING id
)
INSERT INTO event_citations (event_id, url, publisher, publisher_class, is_primary, http_status, fetched_at, note)
SELECT id, 'https://www.cnbc.com/2026/04/20/amazon-invest-up-to-25-billion-in-anthropic-part-of-ai-infrastructure.html', 'cnbc.com', 'news',
       FALSE,
       200, '2026-08-30T02:35:08.316Z'::timestamptz, NULL
  FROM upserted
ON CONFLICT (event_id, url) DO UPDATE SET
  publisher = EXCLUDED.publisher, publisher_class = EXCLUDED.publisher_class,
  is_primary = EXCLUDED.is_primary,
  http_status = EXCLUDED.http_status, fetched_at = EXCLUDED.fetched_at,
  note = EXCLUDED.note;

-- row  8 · Anthropic PBC → AWS
-- long-term cloud spend commitment
WITH upserted AS (
  INSERT INTO events (
    kind, status, from_entity_id, to_entity_id,
    amount_usd, amount_basis, amount_is_estimate,
    announced_date, completed_date, location_iso3,
    headline, confidence_tier, is_verified, dedup_hash,
    loop_status, loop_description, structure_label, is_bidirectional
  ) VALUES (
    'offtake', 'announced', 'anthropic', 'amazon',
    100000000000, 'commitment', FALSE,
    '2026-04-20', NULL, NULL,
    'Anthropic → Amazon: long-term cloud spend commitment ($100bn commitment)', 'news_derived', FALSE, '10f9f144ab358b724ceffd126c44bebab23b22ad47a5854fd51ac0afd2084cfe',
    'forms_loop', 'Anthropic commits to spend $100B on AWS over 10 years tied to expanded Amazon investment', 'long-term cloud spend commitment', FALSE
  )
  ON CONFLICT (dedup_hash) DO UPDATE SET
    kind = EXCLUDED.kind, status = EXCLUDED.status,
    from_entity_id = EXCLUDED.from_entity_id, to_entity_id = EXCLUDED.to_entity_id,
    amount_usd = EXCLUDED.amount_usd, amount_basis = EXCLUDED.amount_basis,
    announced_date = EXCLUDED.announced_date, completed_date = EXCLUDED.completed_date,
    location_iso3 = EXCLUDED.location_iso3, headline = EXCLUDED.headline,
    confidence_tier = EXCLUDED.confidence_tier,
    loop_status = EXCLUDED.loop_status, loop_description = EXCLUDED.loop_description,
    structure_label = EXCLUDED.structure_label,
    is_bidirectional = EXCLUDED.is_bidirectional,
    updated_at = now()
  RETURNING id
)
INSERT INTO event_citations (event_id, url, publisher, publisher_class, is_primary, http_status, fetched_at, note)
SELECT id, 'https://tech-insider.org/amazon-anthropic-5-billion-investment-trainium-2026/', 'tech-insider.org', 'aggregator',
       FALSE,
       200, '2026-08-30T02:35:08.382Z'::timestamptz, NULL
  FROM upserted
ON CONFLICT (event_id, url) DO UPDATE SET
  publisher = EXCLUDED.publisher, publisher_class = EXCLUDED.publisher_class,
  is_primary = EXCLUDED.is_primary,
  http_status = EXCLUDED.http_status, fetched_at = EXCLUDED.fetched_at,
  note = EXCLUDED.note;

-- row  9 · Alphabet Google → Anthropic PBC
-- equity investment
WITH upserted AS (
  INSERT INTO events (
    kind, status, from_entity_id, to_entity_id,
    amount_usd, amount_basis, amount_is_estimate,
    announced_date, completed_date, location_iso3,
    headline, confidence_tier, is_verified, dedup_hash,
    loop_status, loop_description, structure_label, is_bidirectional
  ) VALUES (
    'investment', 'announced', 'alphabet', 'anthropic',
    2000000000, 'commitment', FALSE,
    '2023-10-27', NULL, NULL,
    'Google → Anthropic: equity investment ($2bn commitment)', 'news_derived', FALSE, 'eaef95140aeded7c54f02fc2d507c2cb0cd3120d1616174190662b330373f090',
    'forms_loop', 'Google agrees to invest up to $2B in Anthropic (500M upfront, 1.5B over time) with preferred-cloud status', 'equity investment', FALSE
  )
  ON CONFLICT (dedup_hash) DO UPDATE SET
    kind = EXCLUDED.kind, status = EXCLUDED.status,
    from_entity_id = EXCLUDED.from_entity_id, to_entity_id = EXCLUDED.to_entity_id,
    amount_usd = EXCLUDED.amount_usd, amount_basis = EXCLUDED.amount_basis,
    announced_date = EXCLUDED.announced_date, completed_date = EXCLUDED.completed_date,
    location_iso3 = EXCLUDED.location_iso3, headline = EXCLUDED.headline,
    confidence_tier = EXCLUDED.confidence_tier,
    loop_status = EXCLUDED.loop_status, loop_description = EXCLUDED.loop_description,
    structure_label = EXCLUDED.structure_label,
    is_bidirectional = EXCLUDED.is_bidirectional,
    updated_at = now()
  RETURNING id
)
INSERT INTO event_citations (event_id, url, publisher, publisher_class, is_primary, http_status, fetched_at, note)
SELECT id, 'https://www.reuters.com/technology/google-agrees-invest-up-2-bln-openai-rival-anthropic-wsj-2023-10-27/', 'reuters.com', 'wire',
       FALSE,
       401, '2026-08-30T02:35:08.465Z'::timestamptz, 'unconfirmed: HTTP 401'
  FROM upserted
ON CONFLICT (event_id, url) DO UPDATE SET
  publisher = EXCLUDED.publisher, publisher_class = EXCLUDED.publisher_class,
  is_primary = EXCLUDED.is_primary,
  http_status = EXCLUDED.http_status, fetched_at = EXCLUDED.fetched_at,
  note = EXCLUDED.note;

-- row 10 · Anthropic PBC → Google Cloud
-- preferred cloud provider arrangement
WITH upserted AS (
  INSERT INTO events (
    kind, status, from_entity_id, to_entity_id,
    amount_usd, amount_basis, amount_is_estimate,
    announced_date, completed_date, location_iso3,
    headline, confidence_tier, is_verified, dedup_hash,
    loop_status, loop_description, structure_label, is_bidirectional
  ) VALUES (
    'partnership', 'announced', 'anthropic', 'alphabet',
    NULL, NULL, FALSE,
    '2023-10-27', NULL, NULL,
    'Anthropic → Google: preferred cloud provider arrangement', 'news_derived', FALSE, '0e1e7549b8fd327282819ff86da8931e905316a0eeb67928b70a82a6de02382f',
    'forms_loop', 'Anthropic makes Google its preferred cloud provider and co-develops AI computing systems on GCP', 'preferred cloud provider arrangement', FALSE
  )
  ON CONFLICT (dedup_hash) DO UPDATE SET
    kind = EXCLUDED.kind, status = EXCLUDED.status,
    from_entity_id = EXCLUDED.from_entity_id, to_entity_id = EXCLUDED.to_entity_id,
    amount_usd = EXCLUDED.amount_usd, amount_basis = EXCLUDED.amount_basis,
    announced_date = EXCLUDED.announced_date, completed_date = EXCLUDED.completed_date,
    location_iso3 = EXCLUDED.location_iso3, headline = EXCLUDED.headline,
    confidence_tier = EXCLUDED.confidence_tier,
    loop_status = EXCLUDED.loop_status, loop_description = EXCLUDED.loop_description,
    structure_label = EXCLUDED.structure_label,
    is_bidirectional = EXCLUDED.is_bidirectional,
    updated_at = now()
  RETURNING id
)
INSERT INTO event_citations (event_id, url, publisher, publisher_class, is_primary, http_status, fetched_at, note)
SELECT id, 'https://www.datacenterdynamics.com/en/news/uks-cma-launches-investigation-into-googles-investment-in-anthropic/', 'datacenterdynamics.com', 'trade_press',
       FALSE,
       200, '2026-08-30T02:35:08.606Z'::timestamptz, NULL
  FROM upserted
ON CONFLICT (event_id, url) DO UPDATE SET
  publisher = EXCLUDED.publisher, publisher_class = EXCLUDED.publisher_class,
  is_primary = EXCLUDED.is_primary,
  http_status = EXCLUDED.http_status, fetched_at = EXCLUDED.fetched_at,
  note = EXCLUDED.note;

-- row 11 · Microsoft → Mistral AI
-- minority equity investment
WITH upserted AS (
  INSERT INTO events (
    kind, status, from_entity_id, to_entity_id,
    amount_usd, amount_basis, amount_is_estimate,
    announced_date, completed_date, location_iso3,
    headline, confidence_tier, is_verified, dedup_hash,
    loop_status, loop_description, structure_label, is_bidirectional
  ) VALUES (
    'convertible_note', 'announced', 'microsoft', 'mistral',
    16300000, 'disclosed_total', FALSE,
    '2024-02-26', NULL, NULL,
    'Microsoft → Mistral AI: minority equity investment ($16.3m disclosed)', 'news_derived', FALSE, '5db1b18945b4a075a89e9679cdce03c475e9272c8392bb61c4d9467ee0fc508c',
    'alleged', 'Microsoft invests €15M (~$16.3M) in Mistral as Series A extension alongside Azure distribution deal', 'minority equity investment', FALSE
  )
  ON CONFLICT (dedup_hash) DO UPDATE SET
    kind = EXCLUDED.kind, status = EXCLUDED.status,
    from_entity_id = EXCLUDED.from_entity_id, to_entity_id = EXCLUDED.to_entity_id,
    amount_usd = EXCLUDED.amount_usd, amount_basis = EXCLUDED.amount_basis,
    announced_date = EXCLUDED.announced_date, completed_date = EXCLUDED.completed_date,
    location_iso3 = EXCLUDED.location_iso3, headline = EXCLUDED.headline,
    confidence_tier = EXCLUDED.confidence_tier,
    loop_status = EXCLUDED.loop_status, loop_description = EXCLUDED.loop_description,
    structure_label = EXCLUDED.structure_label,
    is_bidirectional = EXCLUDED.is_bidirectional,
    updated_at = now()
  RETURNING id
)
INSERT INTO event_citations (event_id, url, publisher, publisher_class, is_primary, http_status, fetched_at, note)
SELECT id, 'https://techcrunch.com/2024/02/27/microsoft-made-a-16-million-investment-in-mistral-ai/', 'techcrunch.com', 'news',
       FALSE,
       200, '2026-08-30T02:35:08.672Z'::timestamptz, NULL
  FROM upserted
ON CONFLICT (event_id, url) DO UPDATE SET
  publisher = EXCLUDED.publisher, publisher_class = EXCLUDED.publisher_class,
  is_primary = EXCLUDED.is_primary,
  http_status = EXCLUDED.http_status, fetched_at = EXCLUDED.fetched_at,
  note = EXCLUDED.note;

-- row 12 · Mistral AI → Microsoft Azure
-- cloud distribution partnership
WITH upserted AS (
  INSERT INTO events (
    kind, status, from_entity_id, to_entity_id,
    amount_usd, amount_basis, amount_is_estimate,
    announced_date, completed_date, location_iso3,
    headline, confidence_tier, is_verified, dedup_hash,
    loop_status, loop_description, structure_label, is_bidirectional
  ) VALUES (
    'partnership', 'announced', 'mistral', 'microsoft',
    NULL, NULL, FALSE,
    '2024-05-17', NULL, NULL,
    'Mistral AI → Microsoft: cloud distribution partnership', 'news_derived', FALSE, '8ad6918efc32bd4b50ce0e86efa9e359ad2714ca4b433fcbc53d69973c4a9732',
    'alleged', 'Mistral commits to make flagship models available on Azure and distribute via Azure catalog', 'cloud distribution partnership', FALSE
  )
  ON CONFLICT (dedup_hash) DO UPDATE SET
    kind = EXCLUDED.kind, status = EXCLUDED.status,
    from_entity_id = EXCLUDED.from_entity_id, to_entity_id = EXCLUDED.to_entity_id,
    amount_usd = EXCLUDED.amount_usd, amount_basis = EXCLUDED.amount_basis,
    announced_date = EXCLUDED.announced_date, completed_date = EXCLUDED.completed_date,
    location_iso3 = EXCLUDED.location_iso3, headline = EXCLUDED.headline,
    confidence_tier = EXCLUDED.confidence_tier,
    loop_status = EXCLUDED.loop_status, loop_description = EXCLUDED.loop_description,
    structure_label = EXCLUDED.structure_label,
    is_bidirectional = EXCLUDED.is_bidirectional,
    updated_at = now()
  RETURNING id
)
INSERT INTO event_citations (event_id, url, publisher, publisher_class, is_primary, http_status, fetched_at, note)
SELECT id, 'https://assets.publishing.service.gov.uk/media/664c6cfd993111924d9d389f/Full_text_decision.pdf', 'assets.publishing.service.gov.uk', 'regulator',
       TRUE,
       200, '2026-08-30T02:35:08.978Z'::timestamptz, NULL
  FROM upserted
ON CONFLICT (event_id, url) DO UPDATE SET
  publisher = EXCLUDED.publisher, publisher_class = EXCLUDED.publisher_class,
  is_primary = EXCLUDED.is_primary,
  http_status = EXCLUDED.http_status, fetched_at = EXCLUDED.fetched_at,
  note = EXCLUDED.note;

-- row 13 · Microsoft → Mistral AI
-- multibillion infrastructure and compute deal
WITH upserted AS (
  INSERT INTO events (
    kind, status, from_entity_id, to_entity_id,
    amount_usd, amount_basis, amount_is_estimate,
    announced_date, completed_date, location_iso3,
    headline, confidence_tier, is_verified, dedup_hash,
    loop_status, loop_description, structure_label, is_bidirectional
  ) VALUES (
    'offtake', 'announced', 'microsoft', 'mistral',
    NULL, 'commitment', FALSE,
    '2026-07-20', NULL, NULL,
    'Microsoft → Mistral AI: multibillion infrastructure and compute deal', 'news_derived', FALSE, '336be3c9224cd4ff65fb6b410101452a0490d1036c299dd7a2e0ec29ebd22c77',
    'forms_loop', 'Microsoft agrees to spend billions on Mistral’s Europe-based GPU capacity and use it for its own cloud/AI services', 'multibillion infrastructure and compute deal', FALSE
  )
  ON CONFLICT (dedup_hash) DO UPDATE SET
    kind = EXCLUDED.kind, status = EXCLUDED.status,
    from_entity_id = EXCLUDED.from_entity_id, to_entity_id = EXCLUDED.to_entity_id,
    amount_usd = EXCLUDED.amount_usd, amount_basis = EXCLUDED.amount_basis,
    announced_date = EXCLUDED.announced_date, completed_date = EXCLUDED.completed_date,
    location_iso3 = EXCLUDED.location_iso3, headline = EXCLUDED.headline,
    confidence_tier = EXCLUDED.confidence_tier,
    loop_status = EXCLUDED.loop_status, loop_description = EXCLUDED.loop_description,
    structure_label = EXCLUDED.structure_label,
    is_bidirectional = EXCLUDED.is_bidirectional,
    updated_at = now()
  RETURNING id
)
INSERT INTO event_citations (event_id, url, publisher, publisher_class, is_primary, http_status, fetched_at, note)
SELECT id, 'https://www.reuters.com/business/microsoft-fund-mistrals-european-ai-expansion-multibillion-dollar-deal-2026-07-21/', 'reuters.com', 'wire',
       FALSE,
       401, '2026-08-30T02:35:09.039Z'::timestamptz, 'unconfirmed: HTTP 401'
  FROM upserted
ON CONFLICT (event_id, url) DO UPDATE SET
  publisher = EXCLUDED.publisher, publisher_class = EXCLUDED.publisher_class,
  is_primary = EXCLUDED.is_primary,
  http_status = EXCLUDED.http_status, fetched_at = EXCLUDED.fetched_at,
  note = EXCLUDED.note;

-- row 14 · Nvidia → CoreWeave
-- minority equity investment in Series B
WITH upserted AS (
  INSERT INTO events (
    kind, status, from_entity_id, to_entity_id,
    amount_usd, amount_basis, amount_is_estimate,
    announced_date, completed_date, location_iso3,
    headline, confidence_tier, is_verified, dedup_hash,
    loop_status, loop_description, structure_label, is_bidirectional
  ) VALUES (
    'investment', 'announced', 'nvidia', 'coreweave',
    100000000, 'disclosed_total', FALSE,
    '2023-04-19', NULL, NULL,
    'Nvidia → CoreWeave: minority equity investment in Series B ($100m disclosed)', 'news_derived', FALSE, '799d0dd7d1157650848515dae2053f0feae30c74ba14bb6ab5bab544e055406c',
    'forms_loop', 'Nvidia invests about $100M in CoreWeave’s $221M Series B to fund GPU-focused cloud expansion', 'minority equity investment in Series B', FALSE
  )
  ON CONFLICT (dedup_hash) DO UPDATE SET
    kind = EXCLUDED.kind, status = EXCLUDED.status,
    from_entity_id = EXCLUDED.from_entity_id, to_entity_id = EXCLUDED.to_entity_id,
    amount_usd = EXCLUDED.amount_usd, amount_basis = EXCLUDED.amount_basis,
    announced_date = EXCLUDED.announced_date, completed_date = EXCLUDED.completed_date,
    location_iso3 = EXCLUDED.location_iso3, headline = EXCLUDED.headline,
    confidence_tier = EXCLUDED.confidence_tier,
    loop_status = EXCLUDED.loop_status, loop_description = EXCLUDED.loop_description,
    structure_label = EXCLUDED.structure_label,
    is_bidirectional = EXCLUDED.is_bidirectional,
    updated_at = now()
  RETURNING id
)
INSERT INTO event_citations (event_id, url, publisher, publisher_class, is_primary, http_status, fetched_at, note)
SELECT id, 'https://techcrunch.com/2023/04/20/coreweave-a-gpu-focused-cloud-compute-provider-lands-221m-investment/', 'techcrunch.com', 'news',
       FALSE,
       200, '2026-08-30T02:35:09.082Z'::timestamptz, NULL
  FROM upserted
ON CONFLICT (event_id, url) DO UPDATE SET
  publisher = EXCLUDED.publisher, publisher_class = EXCLUDED.publisher_class,
  is_primary = EXCLUDED.is_primary,
  http_status = EXCLUDED.http_status, fetched_at = EXCLUDED.fetched_at,
  note = EXCLUDED.note;

-- row 15 · Nvidia → CoreWeave
-- equity investment
WITH upserted AS (
  INSERT INTO events (
    kind, status, from_entity_id, to_entity_id,
    amount_usd, amount_basis, amount_is_estimate,
    announced_date, completed_date, location_iso3,
    headline, confidence_tier, is_verified, dedup_hash,
    loop_status, loop_description, structure_label, is_bidirectional
  ) VALUES (
    'investment', 'announced', 'nvidia', 'coreweave',
    2000000000, 'disclosed_total', FALSE,
    '2026-01-25', NULL, NULL,
    'Nvidia → CoreWeave: equity investment ($2bn disclosed)', 'official', FALSE, '70f92955b8b3b04c1d5be29c7e475f48bbbb764bfd26176abac1c717be79cf7c',
    'forms_loop', 'Nvidia invests $2B in CoreWeave common stock at $87.20 per share becoming second-largest shareholder', 'equity investment', FALSE
  )
  ON CONFLICT (dedup_hash) DO UPDATE SET
    kind = EXCLUDED.kind, status = EXCLUDED.status,
    from_entity_id = EXCLUDED.from_entity_id, to_entity_id = EXCLUDED.to_entity_id,
    amount_usd = EXCLUDED.amount_usd, amount_basis = EXCLUDED.amount_basis,
    announced_date = EXCLUDED.announced_date, completed_date = EXCLUDED.completed_date,
    location_iso3 = EXCLUDED.location_iso3, headline = EXCLUDED.headline,
    confidence_tier = EXCLUDED.confidence_tier,
    loop_status = EXCLUDED.loop_status, loop_description = EXCLUDED.loop_description,
    structure_label = EXCLUDED.structure_label,
    is_bidirectional = EXCLUDED.is_bidirectional,
    updated_at = now()
  RETURNING id
)
INSERT INTO event_citations (event_id, url, publisher, publisher_class, is_primary, http_status, fetched_at, note)
SELECT id, 'https://nvidianews.nvidia.com/news/nvidia-and-coreweave-strengthen-collaboration-to-accelerate-buildout-of-ai-factories', 'nvidianews.nvidia.com', 'company_release',
       TRUE,
       200, '2026-08-30T02:35:09.274Z'::timestamptz, NULL
  FROM upserted
ON CONFLICT (event_id, url) DO UPDATE SET
  publisher = EXCLUDED.publisher, publisher_class = EXCLUDED.publisher_class,
  is_primary = EXCLUDED.is_primary,
  http_status = EXCLUDED.http_status, fetched_at = EXCLUDED.fetched_at,
  note = EXCLUDED.note;

-- row 16 · CoreWeave → Nvidia
-- cloud capacity master services order
WITH upserted AS (
  INSERT INTO events (
    kind, status, from_entity_id, to_entity_id,
    amount_usd, amount_basis, amount_is_estimate,
    announced_date, completed_date, location_iso3,
    headline, confidence_tier, is_verified, dedup_hash,
    loop_status, loop_description, structure_label, is_bidirectional
  ) VALUES (
    'offtake', 'announced', 'nvidia', 'coreweave',
    6300000000, 'commitment', FALSE,
    '2025-09-09', NULL, NULL,
    'Nvidia → CoreWeave: cloud capacity master services order ($6.3bn commitment)', 'official', FALSE, 'e52f440e26fac3c42be7ca2facb935597c03ba9822295551e9b33bb9cb31bfbd',
    'forms_loop', 'Nvidia obligated to purchase residual unsold cloud capacity from CoreWeave through 2032 under $6.3B order', 'cloud capacity master services order', FALSE
  )
  ON CONFLICT (dedup_hash) DO UPDATE SET
    kind = EXCLUDED.kind, status = EXCLUDED.status,
    from_entity_id = EXCLUDED.from_entity_id, to_entity_id = EXCLUDED.to_entity_id,
    amount_usd = EXCLUDED.amount_usd, amount_basis = EXCLUDED.amount_basis,
    announced_date = EXCLUDED.announced_date, completed_date = EXCLUDED.completed_date,
    location_iso3 = EXCLUDED.location_iso3, headline = EXCLUDED.headline,
    confidence_tier = EXCLUDED.confidence_tier,
    loop_status = EXCLUDED.loop_status, loop_description = EXCLUDED.loop_description,
    structure_label = EXCLUDED.structure_label,
    is_bidirectional = EXCLUDED.is_bidirectional,
    updated_at = now()
  RETURNING id
)
INSERT INTO event_citations (event_id, url, publisher, publisher_class, is_primary, http_status, fetched_at, note)
SELECT id, 'https://www.stocktitan.net/sec-filings/CRWV/8-k-core-weave-inc-reports-material-event-634b5d5375de.html', 'stocktitan.net', 'aggregator',
       FALSE,
       200, '2026-08-30T02:35:09.746Z'::timestamptz, NULL
  FROM upserted
ON CONFLICT (event_id, url) DO UPDATE SET
  publisher = EXCLUDED.publisher, publisher_class = EXCLUDED.publisher_class,
  is_primary = EXCLUDED.is_primary,
  http_status = EXCLUDED.http_status, fetched_at = EXCLUDED.fetched_at,
  note = EXCLUDED.note;

-- row 20 · Lambda → Macquarie/IDF lenders
-- GPU-backed loan
WITH upserted AS (
  INSERT INTO events (
    kind, status, from_entity_id, to_entity_id,
    amount_usd, amount_basis, amount_is_estimate,
    announced_date, completed_date, location_iso3,
    headline, confidence_tier, is_verified, dedup_hash,
    loop_status, loop_description, structure_label, is_bidirectional
  ) VALUES (
    'debt_facility', 'announced', 'macquarie', 'lambda',
    500000000, 'disclosed_total', FALSE,
    '2024-04-04', NULL, NULL,
    'Macquarie → Lambda: GPU-backed loan ($500m disclosed)', 'official', FALSE, 'ae73e13d45fbb38ac64443659e456b5671a9e68c820d41531d6be6f261e4df20',
    'forms_loop', 'Lambda secures $500M loan collateralized by Nvidia GPUs to buy H100/H200/Blackwell chips and scale GPU cloud', 'GPU-backed loan', FALSE
  )
  ON CONFLICT (dedup_hash) DO UPDATE SET
    kind = EXCLUDED.kind, status = EXCLUDED.status,
    from_entity_id = EXCLUDED.from_entity_id, to_entity_id = EXCLUDED.to_entity_id,
    amount_usd = EXCLUDED.amount_usd, amount_basis = EXCLUDED.amount_basis,
    announced_date = EXCLUDED.announced_date, completed_date = EXCLUDED.completed_date,
    location_iso3 = EXCLUDED.location_iso3, headline = EXCLUDED.headline,
    confidence_tier = EXCLUDED.confidence_tier,
    loop_status = EXCLUDED.loop_status, loop_description = EXCLUDED.loop_description,
    structure_label = EXCLUDED.structure_label,
    is_bidirectional = EXCLUDED.is_bidirectional,
    updated_at = now()
  RETURNING id
)
INSERT INTO event_citations (event_id, url, publisher, publisher_class, is_primary, http_status, fetched_at, note)
SELECT id, 'https://www.reuters.com/technology/lambda-secures-500-mln-loan-with-nvidia-chips-collateral-2024-04-04/', 'reuters.com', 'wire',
       FALSE,
       401, '2026-08-30T02:35:11.171Z'::timestamptz, 'unconfirmed: HTTP 401'
  FROM upserted
ON CONFLICT (event_id, url) DO UPDATE SET
  publisher = EXCLUDED.publisher, publisher_class = EXCLUDED.publisher_class,
  is_primary = EXCLUDED.is_primary,
  http_status = EXCLUDED.http_status, fetched_at = EXCLUDED.fetched_at,
  note = EXCLUDED.note;

INSERT INTO event_participants (event_id, entity_id, side, role, note)
SELECT id, 'idf', 'from', 'participant', 'Named alongside Macquarie in the Reuters report; share undisclosed.'
  FROM events WHERE dedup_hash = 'ae73e13d45fbb38ac64443659e456b5671a9e68c820d41531d6be6f261e4df20'
ON CONFLICT (event_id, entity_id, side)
  DO UPDATE SET role = EXCLUDED.role, note = EXCLUDED.note;

-- row 23 · Blue Owl funds → IREN Limited
-- compute equipment financing
WITH upserted AS (
  INSERT INTO events (
    kind, status, from_entity_id, to_entity_id,
    amount_usd, amount_basis, amount_is_estimate,
    announced_date, completed_date, location_iso3,
    headline, confidence_tier, is_verified, dedup_hash,
    loop_status, loop_description, structure_label, is_bidirectional
  ) VALUES (
    'debt_facility', 'announced', 'blue_owl', 'iren',
    2400000000, 'disclosed_total', FALSE,
    '2026-08-28', NULL, 'CAN',
    'Blue Owl → IREN: compute equipment financing ($2.4bn disclosed)', 'official', FALSE, '5485cb0e75cd136cc83132f8fe6b53653eaeabd8c93672faed413061c87a59ba',
    'forms_loop', '$2.4B term loan + notes at 9% fund IREN’s purchase of Nvidia Blackwell Ultra GPUs for Canadian campus', 'compute equipment financing', FALSE
  )
  ON CONFLICT (dedup_hash) DO UPDATE SET
    kind = EXCLUDED.kind, status = EXCLUDED.status,
    from_entity_id = EXCLUDED.from_entity_id, to_entity_id = EXCLUDED.to_entity_id,
    amount_usd = EXCLUDED.amount_usd, amount_basis = EXCLUDED.amount_basis,
    announced_date = EXCLUDED.announced_date, completed_date = EXCLUDED.completed_date,
    location_iso3 = EXCLUDED.location_iso3, headline = EXCLUDED.headline,
    confidence_tier = EXCLUDED.confidence_tier,
    loop_status = EXCLUDED.loop_status, loop_description = EXCLUDED.loop_description,
    structure_label = EXCLUDED.structure_label,
    is_bidirectional = EXCLUDED.is_bidirectional,
    updated_at = now()
  RETURNING id
)
INSERT INTO event_citations (event_id, url, publisher, publisher_class, is_primary, http_status, fetched_at, note)
SELECT id, 'https://www.prnewswire.com/news-releases/blue-owl-managed-funds-lead-2-4-billion-ai-factory-financing-for-iren-302863057.html', 'prnewswire.com', 'company_release',
       TRUE,
       200, '2026-08-30T02:35:11.459Z'::timestamptz, NULL
  FROM upserted
ON CONFLICT (event_id, url) DO UPDATE SET
  publisher = EXCLUDED.publisher, publisher_class = EXCLUDED.publisher_class,
  is_primary = EXCLUDED.is_primary,
  http_status = EXCLUDED.http_status, fetched_at = EXCLUDED.fetched_at,
  note = EXCLUDED.note;

-- row 27 · MGX → Aligned Data Centers
-- leveraged acquisition
WITH upserted AS (
  INSERT INTO events (
    kind, status, from_entity_id, to_entity_id,
    amount_usd, amount_basis, amount_is_estimate,
    announced_date, completed_date, location_iso3,
    headline, confidence_tier, is_verified, dedup_hash,
    loop_status, loop_description, structure_label, is_bidirectional
  ) VALUES (
    'acquisition', 'announced', 'mgx', 'aligned',
    40000000000, 'disclosed_total', FALSE,
    '2025-10-15', NULL, NULL,
    'MGX → Aligned Data Centers: leveraged acquisition ($40bn disclosed)', 'news_derived', FALSE, '8f083f52d9aba75df964c72fdd85af488d2a327230efcf4b1f092cc89eb9b776',
    'forms_loop', 'MGX joins Nvidia, Microsoft, BlackRock and xAI to buy Aligned Data Centers for ~$40B', 'leveraged acquisition', FALSE
  )
  ON CONFLICT (dedup_hash) DO UPDATE SET
    kind = EXCLUDED.kind, status = EXCLUDED.status,
    from_entity_id = EXCLUDED.from_entity_id, to_entity_id = EXCLUDED.to_entity_id,
    amount_usd = EXCLUDED.amount_usd, amount_basis = EXCLUDED.amount_basis,
    announced_date = EXCLUDED.announced_date, completed_date = EXCLUDED.completed_date,
    location_iso3 = EXCLUDED.location_iso3, headline = EXCLUDED.headline,
    confidence_tier = EXCLUDED.confidence_tier,
    loop_status = EXCLUDED.loop_status, loop_description = EXCLUDED.loop_description,
    structure_label = EXCLUDED.structure_label,
    is_bidirectional = EXCLUDED.is_bidirectional,
    updated_at = now()
  RETURNING id
)
INSERT INTO event_citations (event_id, url, publisher, publisher_class, is_primary, http_status, fetched_at, note)
SELECT id, 'https://www.cnbc.com/2025/10/15/abu-dhabis-mgx-investments-in-trump-crypto-tiktok-openai-.html', 'cnbc.com', 'news',
       FALSE,
       200, '2026-08-30T02:35:13.102Z'::timestamptz, NULL
  FROM upserted
ON CONFLICT (event_id, url) DO UPDATE SET
  publisher = EXCLUDED.publisher, publisher_class = EXCLUDED.publisher_class,
  is_primary = EXCLUDED.is_primary,
  http_status = EXCLUDED.http_status, fetched_at = EXCLUDED.fetched_at,
  note = EXCLUDED.note;

-- row 29 · HUMAIN (PIF-owned) → xAI
-- Series E equity investment
WITH upserted AS (
  INSERT INTO events (
    kind, status, from_entity_id, to_entity_id,
    amount_usd, amount_basis, amount_is_estimate,
    announced_date, completed_date, location_iso3,
    headline, confidence_tier, is_verified, dedup_hash,
    loop_status, loop_description, structure_label, is_bidirectional
  ) VALUES (
    'investment', 'announced', 'humain', 'xai',
    3000000000, 'disclosed_total', FALSE,
    '2026-02-18', NULL, NULL,
    'HUMAIN → xAI: Series E equity investment ($3bn disclosed)', 'news_derived', FALSE, '3f082e16e0f5973db86e15755be9c754f1c2fedeeed23d5b24cd104bec7f8eab',
    'forms_loop', 'HUMAIN invests $3B in xAI as part of $20B Series E anchored by QIA and MGX prior to xAI–SpaceX merger', 'Series E equity investment', FALSE
  )
  ON CONFLICT (dedup_hash) DO UPDATE SET
    kind = EXCLUDED.kind, status = EXCLUDED.status,
    from_entity_id = EXCLUDED.from_entity_id, to_entity_id = EXCLUDED.to_entity_id,
    amount_usd = EXCLUDED.amount_usd, amount_basis = EXCLUDED.amount_basis,
    announced_date = EXCLUDED.announced_date, completed_date = EXCLUDED.completed_date,
    location_iso3 = EXCLUDED.location_iso3, headline = EXCLUDED.headline,
    confidence_tier = EXCLUDED.confidence_tier,
    loop_status = EXCLUDED.loop_status, loop_description = EXCLUDED.loop_description,
    structure_label = EXCLUDED.structure_label,
    is_bidirectional = EXCLUDED.is_bidirectional,
    updated_at = now()
  RETURNING id
)
INSERT INTO event_citations (event_id, url, publisher, publisher_class, is_primary, http_status, fetched_at, note)
SELECT id, 'https://www.fwdstart.me/p/saudi-arabia-humain-invested-3b-in-musk-s-xai-before-spacex-acquisition-now-holds-spacex-shares', 'fwdstart.me', 'newsletter',
       FALSE,
       200, '2026-08-30T02:35:13.775Z'::timestamptz, NULL
  FROM upserted
ON CONFLICT (event_id, url) DO UPDATE SET
  publisher = EXCLUDED.publisher, publisher_class = EXCLUDED.publisher_class,
  is_primary = EXCLUDED.is_primary,
  http_status = EXCLUDED.http_status, fetched_at = EXCLUDED.fetched_at,
  note = EXCLUDED.note;

-- row 30 · HUMAIN → Saudi National Infrastructure Fund
-- AI/digital infrastructure financing agreement
WITH upserted AS (
  INSERT INTO events (
    kind, status, from_entity_id, to_entity_id,
    amount_usd, amount_basis, amount_is_estimate,
    announced_date, completed_date, location_iso3,
    headline, confidence_tier, is_verified, dedup_hash,
    loop_status, loop_description, structure_label, is_bidirectional
  ) VALUES (
    'credit_facility', 'announced', 'saudi_nif', 'humain',
    1200000000, 'commitment', FALSE,
    '2026-01-15', NULL, 'SAU',
    'Saudi National Infrastructure Fund → HUMAIN: AI/digital infrastructure financing agreement ($1.2bn commitment)', 'news_derived', FALSE, 'f3345f623319a52a21d28de7ea4c876aef6cafd09613776ca58142787a9c8e05',
    'alleged', 'HUMAIN signs up to $1.2B financing to expand Saudi AI and digital infrastructure', 'AI/digital infrastructure financing agreement', FALSE
  )
  ON CONFLICT (dedup_hash) DO UPDATE SET
    kind = EXCLUDED.kind, status = EXCLUDED.status,
    from_entity_id = EXCLUDED.from_entity_id, to_entity_id = EXCLUDED.to_entity_id,
    amount_usd = EXCLUDED.amount_usd, amount_basis = EXCLUDED.amount_basis,
    announced_date = EXCLUDED.announced_date, completed_date = EXCLUDED.completed_date,
    location_iso3 = EXCLUDED.location_iso3, headline = EXCLUDED.headline,
    confidence_tier = EXCLUDED.confidence_tier,
    loop_status = EXCLUDED.loop_status, loop_description = EXCLUDED.loop_description,
    structure_label = EXCLUDED.structure_label,
    is_bidirectional = EXCLUDED.is_bidirectional,
    updated_at = now()
  RETURNING id
)
INSERT INTO event_citations (event_id, url, publisher, publisher_class, is_primary, http_status, fetched_at, note)
SELECT id, 'https://www.fwdstart.me/p/saudi-arabia-humain-invested-3b-in-musk-s-xai-before-spacex-acquisition-now-holds-spacex-shares', 'fwdstart.me', 'newsletter',
       FALSE,
       200, '2026-08-30T02:35:13.775Z'::timestamptz, NULL
  FROM upserted
ON CONFLICT (event_id, url) DO UPDATE SET
  publisher = EXCLUDED.publisher, publisher_class = EXCLUDED.publisher_class,
  is_primary = EXCLUDED.is_primary,
  http_status = EXCLUDED.http_status, fetched_at = EXCLUDED.fetched_at,
  note = EXCLUDED.note;

-- row 31 · NAVER → Brookfield
-- AI factory financing agreement
WITH upserted AS (
  INSERT INTO events (
    kind, status, from_entity_id, to_entity_id,
    amount_usd, amount_basis, amount_is_estimate,
    announced_date, completed_date, location_iso3,
    headline, confidence_tier, is_verified, dedup_hash,
    loop_status, loop_description, structure_label, is_bidirectional
  ) VALUES (
    'investment', 'announced', 'brookfield', 'naver',
    9000000000, 'commitment', FALSE,
    '2026-07-25', NULL, 'KOR',
    'Brookfield → NAVER: AI factory financing agreement ($9bn commitment)', 'official', FALSE, '50f0dc81bb5d3b72bd0db184194a291a1c386d5d8b4c00b1b5c5ee5e4705375d',
    'forms_loop', 'Brookfield funds up to $9B to expand NAVER’s GAK Sejong AI factory from 55MW to 200MW; NAVER funds remainder', 'AI factory financing agreement', FALSE
  )
  ON CONFLICT (dedup_hash) DO UPDATE SET
    kind = EXCLUDED.kind, status = EXCLUDED.status,
    from_entity_id = EXCLUDED.from_entity_id, to_entity_id = EXCLUDED.to_entity_id,
    amount_usd = EXCLUDED.amount_usd, amount_basis = EXCLUDED.amount_basis,
    announced_date = EXCLUDED.announced_date, completed_date = EXCLUDED.completed_date,
    location_iso3 = EXCLUDED.location_iso3, headline = EXCLUDED.headline,
    confidence_tier = EXCLUDED.confidence_tier,
    loop_status = EXCLUDED.loop_status, loop_description = EXCLUDED.loop_description,
    structure_label = EXCLUDED.structure_label,
    is_bidirectional = EXCLUDED.is_bidirectional,
    updated_at = now()
  RETURNING id
)
INSERT INTO event_citations (event_id, url, publisher, publisher_class, is_primary, http_status, fetched_at, note)
SELECT id, 'https://finance.yahoo.com/technology/ai/articles/naver-partners-brookfield-nvidia-expand-063200248.html', 'finance.yahoo.com', 'aggregator',
       FALSE,
       200, '2026-08-30T02:35:14.304Z'::timestamptz, NULL
  FROM upserted
ON CONFLICT (event_id, url) DO UPDATE SET
  publisher = EXCLUDED.publisher, publisher_class = EXCLUDED.publisher_class,
  is_primary = EXCLUDED.is_primary,
  http_status = EXCLUDED.http_status, fetched_at = EXCLUDED.fetched_at,
  note = EXCLUDED.note;

-- row 32 · NAVER → Nvidia
-- AI factory equity/computing partnership
WITH upserted AS (
  INSERT INTO events (
    kind, status, from_entity_id, to_entity_id,
    amount_usd, amount_basis, amount_is_estimate,
    announced_date, completed_date, location_iso3,
    headline, confidence_tier, is_verified, dedup_hash,
    loop_status, loop_description, structure_label, is_bidirectional
  ) VALUES (
    'investment', 'announced', 'nvidia', 'naver',
    1000000000, 'commitment', FALSE,
    '2026-07-25', NULL, 'KOR',
    'Nvidia → NAVER: AI factory equity/computing partnership ($1bn commitment)', 'official', FALSE, '363588fcdf23bdfd169b1d2c7552f47181afd29e98212e90b32c69da5e24cb32',
    'forms_loop', 'Nvidia invests $1B and provides DSX platform and GPUs for NAVER’s 200MW sovereign AI factory', 'AI factory equity/computing partnership', FALSE
  )
  ON CONFLICT (dedup_hash) DO UPDATE SET
    kind = EXCLUDED.kind, status = EXCLUDED.status,
    from_entity_id = EXCLUDED.from_entity_id, to_entity_id = EXCLUDED.to_entity_id,
    amount_usd = EXCLUDED.amount_usd, amount_basis = EXCLUDED.amount_basis,
    announced_date = EXCLUDED.announced_date, completed_date = EXCLUDED.completed_date,
    location_iso3 = EXCLUDED.location_iso3, headline = EXCLUDED.headline,
    confidence_tier = EXCLUDED.confidence_tier,
    loop_status = EXCLUDED.loop_status, loop_description = EXCLUDED.loop_description,
    structure_label = EXCLUDED.structure_label,
    is_bidirectional = EXCLUDED.is_bidirectional,
    updated_at = now()
  RETURNING id
)
INSERT INTO event_citations (event_id, url, publisher, publisher_class, is_primary, http_status, fetched_at, note)
SELECT id, 'https://www.theglobeandmail.com/investing/markets/stocks/BAM/pressreleases/3499694/brookfield-boosts-global-ai-infrastructure-wi', 'theglobeandmail.com', 'news',
       FALSE,
       200, '2026-08-30T02:35:16.160Z'::timestamptz, NULL
  FROM upserted
ON CONFLICT (event_id, url) DO UPDATE SET
  publisher = EXCLUDED.publisher, publisher_class = EXCLUDED.publisher_class,
  is_primary = EXCLUDED.is_primary,
  http_status = EXCLUDED.http_status, fetched_at = EXCLUDED.fetched_at,
  note = EXCLUDED.note;

-- row 33 · TSMC Arizona → U.S. Department of Commerce
-- CHIPS Act grant and loan package
WITH upserted AS (
  INSERT INTO events (
    kind, status, from_entity_id, to_entity_id,
    amount_usd, amount_basis, amount_is_estimate,
    announced_date, completed_date, location_iso3,
    headline, confidence_tier, is_verified, dedup_hash,
    loop_status, loop_description, structure_label, is_bidirectional
  ) VALUES (
    'government_grant', 'announced', 'us_commerce', 'tsmc_arizona',
    11600000000, 'commitment', FALSE,
    '2024-04-07', NULL, 'USA',
    'US Department of Commerce → TSMC Arizona: CHIPS Act grant and loan package ($11.6bn commitment)', 'official', FALSE, '6a038f168e8c353586ef285e393cd0dd64a6b2e60c5739b4a5cdd8a2ef4813bb',
    'alleged', 'TSMC awarded up to $6.6B grants and up to $5B loans to support $65B Arizona fabs serving AI chip customers', 'CHIPS Act grant and loan package', FALSE
  )
  ON CONFLICT (dedup_hash) DO UPDATE SET
    kind = EXCLUDED.kind, status = EXCLUDED.status,
    from_entity_id = EXCLUDED.from_entity_id, to_entity_id = EXCLUDED.to_entity_id,
    amount_usd = EXCLUDED.amount_usd, amount_basis = EXCLUDED.amount_basis,
    announced_date = EXCLUDED.announced_date, completed_date = EXCLUDED.completed_date,
    location_iso3 = EXCLUDED.location_iso3, headline = EXCLUDED.headline,
    confidence_tier = EXCLUDED.confidence_tier,
    loop_status = EXCLUDED.loop_status, loop_description = EXCLUDED.loop_description,
    structure_label = EXCLUDED.structure_label,
    is_bidirectional = EXCLUDED.is_bidirectional,
    updated_at = now()
  RETURNING id
)
INSERT INTO event_citations (event_id, url, publisher, publisher_class, is_primary, http_status, fetched_at, note)
SELECT id, 'https://www.nist.gov/chips/tsmc-arizona-phoenix', 'nist.gov', 'regulator',
       TRUE,
       200, '2026-08-30T02:35:16.497Z'::timestamptz, NULL
  FROM upserted
ON CONFLICT (event_id, url) DO UPDATE SET
  publisher = EXCLUDED.publisher, publisher_class = EXCLUDED.publisher_class,
  is_primary = EXCLUDED.is_primary,
  http_status = EXCLUDED.http_status, fetched_at = EXCLUDED.fetched_at,
  note = EXCLUDED.note;

-- row  5 · Amazon → Anthropic PBC
-- COMPLETION of row 3, not a second deal. Amazon completing the $4bn it announced in September 2023 is the SAME $4bn. Loading it as a second event puts $8bn in the table for $4bn of money, and dedup_hash cannot catch it because the dates genuinely differ.
UPDATE events
   SET status = 'completed',
       completed_date = '2024-03-26',
       updated_at = now()
 WHERE dedup_hash = '9bcaf9610ef47ff056247f6239ee89cd989999af1327c13bc30d02186dfe646c';

INSERT INTO event_citations (event_id, url, publisher, publisher_class, is_primary, http_status, fetched_at, note)
SELECT id, 'https://www.aboutamazon.com/news/company-news/amazon-anthropic-ai-investment', 'aboutamazon.com', 'company_release',
       TRUE,
       200, '2026-08-30T02:35:07.166Z'::timestamptz, NULL
  FROM events WHERE dedup_hash = '9bcaf9610ef47ff056247f6239ee89cd989999af1327c13bc30d02186dfe646c'
ON CONFLICT (event_id, url) DO UPDATE SET
  publisher_class = EXCLUDED.publisher_class,
  http_status = EXCLUDED.http_status, fetched_at = EXCLUDED.fetched_at, note = EXCLUDED.note;
