-- 052_economic_intervention.sql
-- Agent-authored economic review, 10 September 2026.
-- Apply to a staging copy first. Does not activate questions, ingest numbers,
-- certify legacy figures, or record a human review.
-- The source ledger records exactly which document sections were consulted.
-- The 40 findings are reframed to the estimands the available charts can support.
-- Quantified legacy captions remain a separate row-level verification worklist.
-- New claims are drafts; source presence is NOT a completed review event.

CREATE TEMP TABLE editorial_052 (
 id TEXT PRIMARY KEY, answer_plain TEXT, answer_expert TEXT, theory TEXT,
 method TEXT, caveat TEXT, geography TEXT, period TEXT, change_trigger TEXT,
 source_keys TEXT[]
) ON COMMIT DROP;

INSERT INTO editorial_052 VALUES
('adoption',
 'AI use is spreading, but adoption is not the same as intensity or economic impact. Enterprise surveys measure reported use; corporate filings measure what firms disclose; cloud uptake measures enabling infrastructure. Read them together as different stages of diffusion, not as interchangeable estimates of how much work AI performs.',
 'The enterprise survey is the direct adoption measure for its defined business population. SEC disclosure incidence includes discussion of risks and plans, and cloud use can occur without AI. Neither the levels nor their differences identify adoption intensity. A claim about unusually rapid historical diffusion requires comparable adopter populations and time since availability.',
 'If firms adopt AI in tasks where it improves quality or lowers total costs, measured use can precede economic gains. Trial use may instead remain shallow or require costly organisational changes; broad uptake alone does not guarantee a large productivity effect.',
 'Start with the same survey definition, sector and enterprise-size threshold across waves. Compare countries only where their populations and reference periods match. Show filings and cloud uptake as context, and use survey documentation to identify breaks rather than inferring them from a jump.',
 'The survey excludes parts of the business population and records whether AI is used, not how intensively. Public-company disclosures are a selected sample. Sector and country averages conceal variation within firms.',
 'EU survey population; US public-company disclosures; separate national comparators',
 'Survey and filing windows shown in each chart; no common historical diffusion window',
 'A comparable intensity measure or a documented survey break changes the interpretation.',
 ARRAY['eurostat-ai','acemoglu']),

('money',
 'The investment charts describe spending on the infrastructure around AI, not an audited total for AI itself. Computing equipment, software and data-centre structures capture different parts of the build-out. Their growth is economically relevant, but broad ICT expenditure also finances activities unrelated to AI.',
 'Separate investment flows, productive capital stocks and capital services per worker. When the relevant asset price falls, real investment can grow faster than nominal spending. Capital deepening additionally depends on depreciation and labour input. Annual structures spending and quarterly annualised ICT flows must retain their own period conventions.',
 'New equipment and complementary software can expand productive capacity. The return depends on utilisation, organisational change and demand; spending can also overshoot profitable uses. Investment need not precede every gain when firms use existing or rented infrastructure.',
 'Read each asset category separately, deflate with a matched price measure where available, and compare spending with GDP only on a consistent nominal basis. R&D and venture funding provide context but are not independent estimates of AI capital formation.',
 'ICT is broader than AI; structures omit hardware and many intangible costs. Short histories cannot establish a pre-AI trend, and expenditure revisions may change historical comparisons.',
 'United States investment; separately labelled R&D comparators',
 'Historical investment series, with annual and quarterly annualised periods distinguished',
 'Matched real investment, asset stocks and utilisation would support a stronger return-to-capital assessment.',
 ARRAY['bea-real','bls-productivity','jcurve']),

('building',
 'The public register shows disclosed computing facilities and capacity estimates. That is evidence about documented infrastructure, not proof that every announced megawatt is operating or that it has consumed electricity. The useful distinction is between plans, construction and commissioned capacity.',
 'Capacity is a power rating, while electricity use is energy over time. The register is incomplete and may include planned systems; additions to the register can reflect discovery rather than new construction. Manufacturing and grid series measure different parts of the supply chain.',
 'A growing compute sector needs equipment, sites and electricity, but efficiency gains and spare capacity can change the relationship between workload and new construction. A project announcement is an option on future capacity, not realised output.',
 'Separate operational status and announcement dates before aggregating facilities. Read capacity alongside actual construction spending and geographically relevant electricity demand; do not treat national generation as a direct meter of data-centre load.',
 'Disclosure coverage varies by owner and country. Missing recent entries cannot establish a construction slowdown. Nameplate capacity does not reveal utilisation, and non-AI computing shares the same facilities.',
 'Countries covered by the public facility register; national supply-chain comparators',
 'Facility and source observation dates; planned and operating status kept distinct',
 'Verified commissioning dates and metered local load would turn announced capacity into evidence of operation.',
 ARRAY['epoch-clusters','iea-energy']),

('productivity',
 'The aggregate charts do not identify how much AI has changed productivity. Task-level studies can show gains in particular workplaces while national outcomes remain affected by investment, demand and workforce composition. The question is how those local gains spread and survive implementation costs.',
 'Labour productivity, total factor productivity and unit labour costs answer different questions. A flat aggregate series is not a statistical estimate of zero AI effect, and a rise is not attribution. Compare matched growth windows and distinguish forecasts from observations before interpreting any break.',
 'AI can save task time or improve output, while implementation and complementary investment absorb resources. The J-curve is one conditional explanation for delayed measured benefits; weak adoption or limited useful applications are alternatives, not facts the framework rules out.',
 'Use output per hour for labour efficiency, growth accounting for contributions, and workplace studies for mechanisms. Keep national comparisons descriptive unless an explicit identification design supplies a counterfactual. Inspect release vintages and forecast flags.',
 'Microeconomic estimates need not generalise beyond the task, firm or worker group studied. National accounts may miss quality changes and are revised. This page is not a causal null test or a forecast of an inevitable later boom.',
 'United States, United Kingdom and separately labelled comparators',
 'Source-specific productivity histories and paper study periods; forecasts excluded from outturn claims',
 'Matched firm adoption and productivity data, or a credible identified national contribution, would strengthen attribution.',
 ARRAY['bls-productivity','jcurve','acemoglu','ai-work']),

('jobs',
 'Employment composition is changing, but a sector share cannot tell us how much AI caused it. Information-sector trends combine earlier restructuring with the current technology cycle. Firm growth, occupational displacement and local employment losses can coexist because they describe different populations and adjustments.',
 'Dividing sector employment by total payrolls normalises its size; it does not cancel the business cycle or create a control group. A causal comparison would require a defensible exposure measure, comparable trends and a design addressing selection and sector-specific shocks.',
 'Task substitution can reduce demand for some work while lower costs, new tasks and business expansion raise demand elsewhere. The net effect on jobs depends on these competing margins, rather than exposure alone.',
 'Use sector share to describe composition, then examine occupation, age, hiring and separations at their own resolution. Compare studies only after matching outcome, geography, period and exposure definition. Treat industry codes as imperfect proxies for tasks.',
 'Information is not synonymous with AI exposure. Firm and local estimates have different estimands. Interest rates, post-pandemic hiring and pre-existing trends remain rival explanations for sector movements.',
 'US information sector; separately labelled international and research populations',
 'Full sector history and explicitly matched study windows',
 'Occupation-by-age hiring data with validated exposure and a credible comparison group would change the causal assessment.',
 ARRAY['acemoglu','bls-cps','ai-work']),

('entry-level',
 'Entry-level outcomes need to be measured inside occupations and hiring channels. National youth unemployment is too broad to settle whether AI is making career entry harder. Evidence of workplace productivity gains for less-experienced workers also leaves open whether firms hire more of them or need fewer new recruits.',
 'Employment, unemployment and vacancies are distinct outcomes. Age ranges, education groups and occupational exposure definitions must match before estimates are compared. Earlier and revised versions of a paper are not competing bounds on one effect.',
 'AI may automate tasks assigned to new entrants, reducing hiring, or help novices perform better and expand demand for their work. The balance depends on task allocation and firm demand; youth alone is not a measure of exposure.',
 'Treat national youth and graduate rates as context. The direct test uses occupation-by-age employment and hiring, a stated exposure measure and comparable less-exposed groups. Keep descriptive relative gaps separate from causal estimates and preserve paper versions.',
 'Unemployment excludes people outside the labour force and cannot reveal foregone hiring in a small occupation. A productivity study of existing workers does not measure entry-level job creation. The occupational literature below must be read in its own sample.',
 'US youth and graduate groups; national comparators and cited workplace samples',
 'Chart-specific periods; paper versions and age bands explicitly retained',
 'A reproducible occupation-by-age hiring panel would provide a direct test of career-entry changes.',
 ARRAY['bls-cps','ai-work','acemoglu']),

('vacancies',
 'Vacancies are an early measure of recruitment demand, but a fall in one technology sector does not establish AI substitution. Country, sector and period matter: a long decline in a UK vacancy level can coexist with faster recent growth in exposed industries elsewhere.',
 'A vacancy stock is not the number of hires or the flow of redundancies. Rates and counts also differ. An apparent conflict between studies should be tested on a common window and population before the evidence is labelled contested.',
 'AI could reduce recruitment for substitutable tasks, while expansion or a need for complementary skills increases other openings. Macroeconomic demand and hiring normalisation can move vacancies through either channel.',
 'Compare vacancy rates or consistently defined counts over matched seasonal windows. Where available, add hires and separations. Explain the reference population for each country rather than treating a broad industry as a fixed AI-exposure group.',
 'Fewer adverts can reflect slower demand, changed recruitment channels or faster matching. Vacancies alone do not identify worker displacement or prove a skills shortage has ended.',
 'UK information and communication; explicitly labelled OECD comparators',
 'Matched vacancy periods rather than a mixture of long-run levels and recent growth',
 'Comparable exposure-specific vacancy and hiring flows would distinguish recruitment changes from reporting differences.',
 ARRAY['bls-jolts','acemoglu']),

('power',
 'Electricity supply can constrain the location and timing of computing investment. The IEA identifies concentrated data-centre demand and grid bottlenecks as material risks. National industrial tariffs describe the price environment, but cannot establish that power is the binding constraint for every project.',
 'Retail tariffs, wholesale prices, connection costs and available firm capacity are different quantities. A data centre may face a bespoke contract rather than the average industrial price. Nominal tariff movements do not isolate AI-driven demand.',
 'Large new loads can strain a local grid when supply and connections adjust slowly. Siting, flexible operation, efficiency and new generation can ease that constraint; a higher price need not imply an unavoidable national shortage.',
 'Read tariff histories alongside geography, consumption bands and grid-connection evidence. Separate actual load from scenarios and use matched tax treatment in country comparisons. The IEA report supplies a mechanism and outlook, not observations for this dashboard.',
 'National averages conceal local bottlenecks and contracts. Fuel prices, network costs and regulation also change tariffs. Forecast demand should not be presented as metered consumption.',
 'United States and European tariff comparators; IEA global and regional analysis',
 'Historical tariffs; IEA 2025 report scenarios kept separate',
 'Project-level connection delays and actual load matched to local grid capacity would establish where constraints bind.',
 ARRAY['iea-energy','eurostat-power']),

('materials',
 'Metal prices describe part of the cost environment for data-centre construction, but the charts do not identify an AI share of commodity demand. Computing investment competes with other users for materials, so a price rise requires a supply-and-demand explanation beyond the technology narrative.',
 'Commodity prices are not a bill of materials or a measure of demand from AI. The economic question requires quantities, material intensity and supply responsiveness, with currencies and real versus nominal treatment stated.',
 'Additional infrastructure demand can raise input costs where supply responds slowly. Recycling, substitution, inventories and weaker demand from other sectors can offset that pressure; there is no fixed pass-through from AI spending to world prices.',
 'Use dated commodity series as context for build-out costs. Direct attribution would require project material requirements and a commodity balance that includes other demand and supply. Avoid unsourced tonnage or technical-use claims.',
 'Global prices respond to many industries and financial conditions. The dashboard does not currently estimate material intensity or the share of each commodity consumed by data centres.',
 'Global commodity markets; infrastructure context rather than country-specific AI demand',
 'Dates of the displayed commodity observations',
 'Verified bill-of-materials data and sector demand balances would permit an AI-specific contribution estimate.',
 ARRAY['iea-energy']),

('markets',
 'The price of a semiconductor, the price of a hosting contract and the cost of completing an AI task are different measures. Their indices describe parts of the supply chain; they do not by themselves show whether useful computation has become cheaper to buy.',
 'Producer price indices seek to measure price change for defined products. Quality adjustment matters, and a broad hosting basket is not a constant-quality AI task. Rebasing aligns an index origin, not the economic content of its basket.',
 'Cheaper hardware can lower service costs, but energy, labour, margins and quality also change. The observable wedge between two indices cannot allocate the cause among these channels.',
 'Compare within-series price changes over common periods and name the product basket. Keep compute capability and service quality separate from nominal contract prices. Use a task- or performance-adjusted series only when its methodology is available.',
 'A flat chip index need not mean technical progress stopped. A rising hosting index is not proof that the cost per useful computation rose, nor that service providers captured all hardware savings.',
 'United States price indices; separately dated Japanese comparators',
 'Common price-index windows; source end dates displayed',
 'A comparable price per unit of delivered capability would answer the compute-cost question more directly.',
 ARRAY['bls-cloud']),

('policy',
 'The series counts US federal documents matching AI-related terms. It measures publication activity, not the number of AI laws currently in force or the cost of complying with them. Document type helps interpretation, but substantive relevance and legal status require reading the underlying records.',
 'Publication date and effective date are distinct. The rules category can include amendments, withdrawals and other actions; proposal and final-rule counts are not linked cohorts. Counts do not measure regulatory restrictiveness or net obligations.',
 'More publication activity may reflect attention, implementation, revision or deregulation. It need not mean a larger compliance burden or a state responding only after technology adoption.',
 'Deduplicate document identifiers, retain agency, action, effective dates and docket links, and validate keyword relevance on a documented sample. Compare annual flows only after defining the same universe; use current legal records for in-force status.',
 'This is a US keyword-based series. False positives, agency batches and changing terminology can move it. It cannot establish international regulatory coverage or conversion from proposals without linked cases.',
 'United States federal publications',
 'Publication windows shown; effective dates are separate',
 'Document-level relevance and linked regulatory histories would support legal-status and conversion measures.',
 ARRAY['nara']),

('dot-com',
 'The comparison is useful for the shape of computing investment cycles, but nominal spending alone cannot decide which boom was larger in real resources. A defensible size comparison needs both a matched price adjustment and a measure relative to the economy.',
 'Nominal ICT expenditure, real investment and investment as a share of GDP answer different questions. Falling equipment prices can make real investment outgrow nominal spending. Asset definitions must be comparable across the two episodes.',
 'A large computing cycle can raise capacity and later leave overinvestment when expectations exceed demand. Similar chart shapes do not establish identical financing, valuations or future outcomes.',
 'Align the asset basket and episode windows. Present nominal investment/GDP separately from deflated investment. Keep software and equipment distinct and disclose revisions; do not infer a future bust from a historical overlay.',
 'The current cycle is unfinished. Changes in software treatment, asset quality and economy size limit historical comparison, even when a long nominal series is available.',
 'United States computing investment',
 'Historical dot-com and current-cycle windows, aligned within each measure',
 'Matched deflators and investment/GDP series would permit a direct size comparison.',
 ARRAY['bea-real','jcurve']),

('sector-output',
 'The information sector is an important part of the digital economy, but its output is not a measure of AI output. Its long-run growth is useful context; establishing an AI contribution requires separating technology effects from trends that were already present.',
 'Real value added and nominal computer-services exports are different constructs. The industry includes activities beyond AI, and a larger sector is not a necessary condition for productivity gains in its customers.',
 'AI could raise output in supplier industries or lower the price of inputs used elsewhere. Benefits may accrue to customers, so a weak supplier-sector value-added response would not disprove economy-wide gains.',
 'Compare real growth over matched windows, with the industry definition and deflator stated. Treat nominal export values as a separate trade measure. Do not call correlated sector and trade movements independent causal confirmation.',
 'Classification, outsourcing, exchange rates and non-AI demand can change these series. A visual change in slope is not a tested structural break.',
 'US information sector; world computer-services exports as separate context',
 'Matched pre- and post-adoption windows within each source',
 'Industry-level AI adoption and a credible decomposition would sharpen attribution.',
 ARRAY['bls-productivity','acemoglu']),

('exposed-productivity',
 'Comparing an information sector with its economy can reveal a productivity gap, but cannot assign that gap to AI. Pre-existing sector trends and differing shocks must be distinguished from any change associated with adoption.',
 'A sector-minus-economy comparison does not remove all macroeconomic shocks: demand, capital intensity and composition differ. Matching base years makes indices readable but does not create an untreated control.',
 'Higher adoption could produce earlier gains in exposed tasks, but organisational change and sector composition can also drive the gap. Adoption rates need not rank the size of productivity benefits across industries.',
 'Use common periods, consistent output-per-hour definitions and pre-trend checks. Present the EU aggregate as a region, not an independent country replication. A causal design must justify its exposure measure and counterfactual.',
 'Broad industry aggregates conceal firm and task variation. A slowdown does not prove AI had no positive effect relative to what otherwise would have happened.',
 'United Kingdom information and communication and market sector; EU27 comparator',
 'Matched industry and aggregate productivity windows',
 'A defensible comparison design using adoption and pre-trends would change causal confidence.',
 ARRAY['bls-productivity','acemoglu']),

('clerical',
 'The clerical series describe employment in related occupational groups; they do not by themselves identify AI displacement. Differences between national and international classifications should first be reconciled as measurement differences, not treated as disagreement about one precisely defined population.',
 'SOC and ISCO categories, survey coverage and employed-person concepts need a crosswalk. A gap between levels can be entirely definitional. A long decline before generative AI is a baseline to explain, not an estimate of its effect.',
 'Some clerical tasks are candidates for automation, but complementarity and changes in demand can offset substitution. Occupational employment combines these margins and changes in how jobs are classified.',
 'Keep each occupational definition visible. Compare trends over matching years only after documenting coverage; use task exposure and a suitable comparison group for attribution. Show hiring or hours where available.',
 'Related labels do not guarantee equivalent occupations. Levels can differ without either source being wrong, and recent changes can reflect non-AI restructuring.',
 'United States occupational series; separately labelled international definitions',
 'Comparable occupation histories, with classification changes identified',
 'A validated occupational crosswalk and exposure-specific employment panel would strengthen the assessment.',
 ARRAY['bls-cps','acemoglu']),

('total-factor-productivity',
 'Total factor productivity helps separate output growth from measured input growth, but it is not an AI meter. The available histories and forecast vintages must be understood before drawing conclusions about recent technological change.',
 'TFP is a residual within a growth-accounting framework. It can reflect efficiency, scale, resource allocation and measurement issues. Labour productivity can also rise through capital deepening or workforce composition; the difference is not simply an estimate of AI.',
 'AI may improve the use of inputs, while complementary investments and measurement lags complicate its appearance in accounts. The J-curve is a possible mechanism, not evidence that every weak TFP period contains hidden gains.',
 'Keep labour productivity and TFP definitions separate. Use documented growth-accounting contributions and exclude projected or unresolved-vintage values from historical findings. Compare matched real-output and input concepts.',
 'Short post-adoption histories limit inference. A forecast is not an outturn even after its period start date has passed; historical estimates can still be revised.',
 'US and UK TFP; source-specific statistical universes',
 'Historical outturns only for findings; forecast horizons explicitly separated',
 'Updated outturns and a matched growth-accounting decomposition would improve the test.',
 ARRAY['bls-productivity','jcurve']),

('computer-dividend',
 'The ICT contribution to labour-productivity growth and software contribution to capital-stock growth are separate accounting measures. They cannot be divided or contrasted as though they were a return delivered by the same investment flow. The charts are useful only when those denominators stay explicit.',
 'A contribution in percentage points depends on its underlying growth rate and weight. Capital-stock growth is not capital-services growth per hour, and software is not all ICT. A smaller ICT contribution does not by itself imply a lower return on current software spending.',
 'Investment can change productive capital services, while labour input, asset mix and depreciation affect capital deepening. Productivity also changes through other inputs and efficiency.',
 'Read each contribution against the identity it belongs to. A dividend comparison needs consistent asset coverage, capital services, hours and periods. Historical series ending before widespread generative AI adoption provide a baseline, not a post-adoption result.',
 'Do not infer a ratio of returns from unmatched contribution series. Old observations cannot evaluate a later technology cycle.',
 'United States growth-accounting series',
 'Common historical years; coverage end dates retained',
 'Matched ICT capital-services and labour-productivity decompositions would permit a meaningful contribution comparison.',
 ARRAY['bls-productivity']),

('china-mirror',
 'The Chinese series document a digital sector with a history predating generative AI. Revenue, employment, pay and chip output illuminate different aspects of that sector; their growth alone cannot identify an AI contribution or establish a comparison with US outcomes.',
 'Nominal revenue and wages require appropriate deflators for real growth. Urban-unit employment is not the entire labour market, and chip counts do not measure computing capability. Industry boundaries differ across countries.',
 'AI could expand demand and productivity in digital industries, while industrial policy, earlier digitisation and general demand can generate similar movements.',
 'Keep each population and unit explicit, compare like-for-like time windows and show national sources separately. A US-China comparison requires matched definitions rather than currency conversion alone.',
 'The wage series has no economy-wide comparator on this page, and changing sector composition can affect averages. These data are not an AI-specific treatment group.',
 'China, with source-specific industry and urban-unit coverage',
 'Historical source windows rather than an assumed common AI start date',
 'Comparable real measures and direct adoption information would enable a stronger cross-country assessment.',
 ARRAY['bls-productivity','acemoglu']),

('orders-and-output',
 'Production and new orders describe different parts of the computing supply chain. Their relative movements can reveal differences between output and demand signals, but a lower nominal order value than during the dot-com era does not prove real orders are lower.',
 'An industrial-production volume index cannot be read as a nominal orders series. A valid real-orders comparison requires the relevant deflator and stable product coverage; falling electronics prices can reverse the nominal inference.',
 'Orders can precede production, but inventories, imports, delivery lags and product mix affect the link. AI is one potential source of demand among several.',
 'Compare production within its volume index and orders within a consistent nominal or explicitly deflated series. Match periods, separate partial years, and avoid treating the two as independent estimates of AI demand.',
 'Domestic output excludes imported equipment. Industry aggregation and quality change limit historical comparisons, and the orders-output relationship need not be stable.',
 'United States computer and electronic products industries',
 'Matched production and orders windows; no undeflated real comparison',
 'A suitable orders deflator and matched product coverage would settle the real-volume comparison.',
 ARRAY['bea-real','bls-chip']),

('frontier-compute',
 'The record of disclosed training runs measures the known frontier, not every model that has been trained. Growth between named records is descriptive; a missing new record can reflect disclosure gaps and cannot establish that scaling stopped.',
 'Record observations are irregular and selectively disclosed. A compound growth rate between two endpoints is not a statistical test of acceleration, and training compute is not directly comparable with facility capacity or capital spending.',
 'Larger training budgets may improve capability, while algorithms, data and inference-time computation can also matter. Infrastructure demand therefore need not move one-for-one with the largest disclosed training run.',
 'State the two endpoint dates and calculation for each growth window. Separate training workload, cluster capacity and utilisation. Do not interpolate an unreported frontier as a measured plateau.',
 'Disclosure is incomplete and may change over time. Similar historical growth rates cannot establish equal future returns or a causal link from spending to model quality.',
 'Global disclosed training runs; separately labelled facility data',
 'Named record dates, not an assumed continuous annual frontier',
 'New verified model disclosures and a documented sampling process would change the measured frontier.',
 ARRAY['epoch-clusters','iea-energy']),

('chip-prices',
 'The measured semiconductor price index can flatten without establishing that chips stopped improving in price per unit of performance. The manufacturing-equipment index describes another product basket. These charts need a quality-adjustment interpretation before supporting a claim about compute costs.',
 'BLS research shows why a matched-model microprocessor index can behave differently from a hedonic measure when product performance and pricing practices change. That historical result does not supply a corrected index for every recent semiconductor product.',
 'Better hardware can reduce cost per task even when quoted product prices change little. Conversely, scarce advanced equipment or different product mixes can raise particular costs.',
 'Describe changes in the published index as changes in that index. For performance-adjusted conclusions, require an appropriate benchmark and quality method. Keep equipment prices distinct from chip prices and useful AI-task costs.',
 'An older microprocessor methodology study is not a current GPU-price estimate. A flat aggregate index is neither proof of no innovation nor proof that all compute is getting cheaper.',
 'US semiconductor and equipment indices; dated Japanese equipment comparator',
 'Published price-index histories; methodology study covers its stated historical sample',
 'A current matched price-performance series would support a stronger compute-cost finding.',
 ARRAY['bls-chip']),

('bulk-discount',
 'The two consumption bands describe prices paid by groups of electricity users. Their changing gap is informative about observed tariff differences, but it is not a causal estimate of the discount a single buyer receives by purchasing more power.',
 'Country mix, consumption weights, contracts and tax treatment can differ between bands and change over time. Holding band thresholds constant is necessary but not sufficient for a like-for-like buyer comparison.',
 'Large users may secure different contracts, yet exposure to wholesale prices, network costs and location can offset purchasing advantages. An inverted band average does not imply every large buyer paid more.',
 'Compare the same currency, tax basis and semester, then inspect country-level pairs before interpreting an aggregate. Label the ratio as a difference between group averages rather than a quantity discount experiment.',
 'The bands do not follow the same firms as consumption changes. The EU average can move through composition even when national price relationships do not.',
 'EU non-household consumption bands and available national pairs',
 'Matched half-year observations and consistent tax treatment',
 'Matched country weights and contract-level evidence would distinguish composition from buyer-scale effects.',
 ARRAY['eurostat-power']),

('aggregate-unemployment',
 'Aggregate labour-market indicators provide context for claims about AI, not a test that can rule out displacement. Employment can grow while some tasks disappear, and unemployment can remain low even when hiring opportunities weaken in particular occupations.',
 'Unemployment is measured relative to the labour force; payrolls count jobs and are not a population-adjusted employment rate. Neither creates a counterfactual for an economy without AI. An unchanged aggregate is not an estimated zero effect.',
 'Substitution, new tasks, stronger demand and labour-force changes can offset one another. Distributional effects may be important even when net employment changes little.',
 'Keep employment counts, rates and unemployment denominators separate. Use consistent population and partial-year conventions, then connect aggregate context to occupation-level evidence without asserting causation.',
 'Global estimates aggregate diverse surveys and can be modelled or revised. A low unemployment rate does not reveal hours, job quality, participation or foregone job creation.',
 'World unemployment estimate; US and Japanese employment and US youth context',
 'Source-specific historical observations; full-year and partial-year summaries distinguished',
 'A credible counterfactual and distributional employment measures would allow an AI-effect estimate.',
 ARRAY['bls-cps','acemoglu']),

('executive-action',
 'The mix of presidential and agency publications describes the form of federal activity. It does not establish a lasting transfer of regulatory power or compare the amount of binding obligation created by each document.',
 'Executive orders, memoranda, rules and notices have different legal functions. Publication counts alone cannot establish durability, implementation time or whether an action remains effective.',
 'Presidents and agencies can use different instruments to direct policy, while statutes, courts and later actions constrain implementation. A short-lived change in publication mix may be a political or administrative episode.',
 'Retain agency, action and effective-date fields; validate substantive AI relevance and compare equivalent periods. Read linked implementing actions before attributing an obligation to a presidential document.',
 'Draft remains inactive pending document-level validation and refreshed counts. More documents need not mean more restrictive policy, and rules do not automatically survive every later change.',
 'United States federal publications',
 'Matched annual windows; incomplete years distinguished',
 'Validated action types and regulatory histories would support a claim about instrument choice.',
 ARRAY['nara']),

('rule-conversion',
 'Unlinked proposal and rule counts cannot measure conversion. More final-rule publications than proposals in one year is compatible with proposals from earlier years becoming final; it is not a logical contradiction.',
 'A conversion rate requires a cohort, linkage rules, follow-up horizon and treatment of withdrawn or combined actions. Some rules use exceptions to prior notice and comment, so not every final action belongs to the same proposal process.',
 'A proposal may be completed, revised, withdrawn or remain pending. Administrative capacity and legal requirements affect timing; document volume alone does not reveal those transitions.',
 'Link docket and regulatory identifiers, verify substantive matches, and follow proposal cohorts over time. Count distinct actions and report unresolved links instead of treating annual flow ratios as completion rates.',
 'Draft remains inactive until linkage quality and follow-up are measured. Do not claim that no free source can support linkage without testing the available document records.',
 'United States federal proposal cohorts',
 'Cohort entry and follow-up periods, not same-year count ratios',
 'A validated linked sample with explicit pending cases would enable a conversion estimate.',
 ARRAY['nara']),

('policy-lag',
 'The timing of disclosure, investment and regulatory publications can be described, but these series cannot establish whether regulation followed adoption. They measure different activities, and shared attention to AI can move all of them.',
 'A visual ordering of a few turning points is not identification. Keyword coverage, reporting cadence and the public-company sample affect apparent timing. Broad ICT investment does not date AI adoption.',
 'Government may react to adoption, anticipate it or shape incentives; firms and regulators may both respond to a common technological change. The three channels require different evidence.',
 'Use matched jurisdictions and definitions, validate document relevance and date comparable events. Keep the chart as chronology unless a design identifies the direction of response.',
 'Draft remains inactive pending keyword validation and a defensible timing comparison. A later observed publication does not show that policy discussion began later.',
 'United States federal activity, public-company disclosures and broad ICT investment',
 'Matched event and reporting windows',
 'Documented adoption dates and regulatory histories would improve the lead-lag analysis.',
 ARRAY['nara','eurostat-ai']),

('who-funds-it',
 'Investment totals and venture-capital flows cannot identify who finances the AI build-out. They describe different uses and sources of money, often for different populations. A financing answer needs company cash flows and funding instruments linked to the relevant projects.',
 'Capital expenditure is a use of funds; operating cash flow, borrowing and equity issuance are financing sources. Later-stage venture investment is neither all AI funding nor a complete counterpart to national ICT investment.',
 'Internal funds may reduce dependence on new equity, but firms can still cut investment when expected returns or cash flows weaken. Borrowing, leases and partnerships can transmit financial risk even when venture funding is small.',
 'Reconcile company investment with cash-flow statements, debt, leases and equity; define venture stages and AI exposure. Avoid dividing broad national spending by an unrelated venture total.',
 'Draft remains inactive pending matched financing coverage. Corporate investment is not proof of cash-flow funding, and internally financed booms can still reverse.',
 'United States investment and venture context; project/company financing not yet matched',
 'Common company financial periods required',
 'Source-and-use reconciliation for the main investors would support an actual financing thesis.',
 ARRAY['sec-finance','jcurve']),

('expectations',
 'A broad stock-market index cannot isolate what investors are paying for AI. Disclosures and venture activity add context, but none supplies an AI valuation premium or separates earnings expectations from discount-rate changes.',
 'Asset prices respond to expected cash flows, risk and discount rates. A defensible AI-exposure comparison needs a transparent universe and benchmark; a whole-market series cannot perform that decomposition.',
 'AI may change expected profits or the risk attached to them. At the same time, interest rates and non-AI earnings can move the same prices. Rising investment can reflect both opportunity and overoptimism.',
 'Keep the current chart descriptive. Before estimating a premium, define exposure, returns, benchmark factors and event timing, and confirm redistribution rights for the data.',
 'Draft remains inactive pending a suitable licensed benchmark and an editorial decision on the estimand. Corporate mentions are not a valuation model.',
 'United States broad equity market and disclosure context',
 'Matched return windows required for any exposure comparison',
 'A licensed, reproducible exposure portfolio and benchmark would permit a valuation analysis.',
 ARRAY['sec-finance']),

('diffusion-speed',
 'The existing internet and enterprise-AI series do not support a ranking of diffusion speed. One counts people, another counts firms, and their observation windows begin at different stages. Similar percentage-point changes are not evidence of identical diffusion processes.',
 'Match the adopter population, adoption definition and time since availability before comparing curves. Penetration levels, percentage-point gains and proportional growth answer different questions.',
 'Lower adoption costs and complementary infrastructure could speed uptake; organisational frictions and uneven task suitability could slow it. A consumer tool and an enterprise workflow need not diffuse on the same clock.',
 'Use comparable adoption cohorts and consistent denominators. Report enterprise-sector variation directly, but avoid translating a rate gap into a number of years without an estimated diffusion curve.',
 'Draft remains inactive until a comparable historical benchmark is assembled. Survey use does not measure intensity or sustained production deployment.',
 'World internet users versus surveyed enterprises; currently non-comparable populations',
 'Aligned technology-age windows required',
 'A matched population and adoption-stage benchmark would permit a historical speed comparison.',
 ARRAY['eurostat-ai','jcurve']),

('the-buildings',
 'Construction spending measures work put in place, while a capacity register describes facilities and plans. These sources can illuminate the build-out when kept separate. Broad manufacturing construction cannot reveal how much is semiconductor fabrication or AI infrastructure without a verified breakdown.',
 'Structures spending omits equipment and does not equal total project cost. Nominal spending needs a construction deflator for real-volume comparisons, and facility power capacity is a different unit altogether.',
 'New facilities can expand capacity, but construction timing, cancellations and equipment installation separate spending from productive operation. Other manufacturing projects can move the aggregate construction series.',
 'Verify a relevant construction category, its geography and source coverage. Present annual spending, monthly annualised construction and facility status on their own bases; do not add them together.',
 'Draft remains inactive until the construction-category gate is resolved. Short or old series cannot establish the scale of a newer announcement cycle.',
 'United States structures and manufacturing construction; disclosed facility context',
 'Source-specific construction periods and facility status dates',
 'A verified fab/data-centre breakdown with recent observations would support a narrower construction finding.',
 ARRAY['bea-real','epoch-clusters','iea-energy']),

('software-not-steel',
 'Software and hardware investment can behave differently, but software spending should not be described as mostly the salaries of workers who remain employed. Purchased, custom and own-account software are different components, and their measurement must be inspected before explaining resilience.',
 'Own-account production is estimated rather than observed as a market sale. Nominal software investment also reflects prices and the composition of production; it is not a direct count of retained programmers or a financing measure.',
 'Firms may retain complementary software projects during a hardware downturn, but contracts, accounting and labour costs can produce similar patterns. Intangible investment can be valuable without immediately appearing as measured productivity.',
 'Compare the software components on the same accounting basis, then use matched real and nominal series. State whether a quarterly value is annualised and keep hardware and software totals reconciled.',
 'Draft remains inactive pending verified component interpretation and current calculations. The chart cannot establish an employment-retention mechanism on its own.',
 'United States private software and equipment investment',
 'Consistent annual or quarterly annualised windows',
 'Verified software components and matched deflators would distinguish production composition from price changes.',
 ARRAY['bea-real','jcurve']),

('is-europe-in-this',
 'European and US investment statistics can inform the comparison only where their industries and accounting bases match. Nominal R&D growth in different currencies is not a real-capability ranking, and a real European investment index cannot be compared directly with nominal US spending.',
 'Match sector scope, asset definitions and price treatment. Cross-border relocation of intellectual property can alter recorded investment without an equivalent change in local productive capability.',
 'R&D and complementary capital can support AI capability, but spending may produce different returns and may be recorded away from where development or use occurs.',
 'Compare like-for-like real growth or nominal expenditure shares. Inspect national detail before interpreting EU intellectual-property movements, and keep unmatched series as context rather than ranking evidence.',
 'Draft remains inactive pending matched definitions and investigation of IP movements. Similar spending growth does not imply equal AI capability or economic benefit.',
 'European Union and United States; national detail required',
 'Matched R&D and investment periods',
 'Harmonised real measures and location-of-production evidence would support the cross-region assessment.',
 ARRAY['bea-real','jcurve']),

('sector-jobs',
 'A rise in output alongside lower headcount can increase output per worker, but it does not isolate AI. Hours, outsourcing, capital and sector composition can all change the relationship. The page needs a distinct contribution beyond the broader employment-share question.',
 'Employment counts are not hours worked, and output per worker is not total factor productivity. A sector-level comparison cannot establish whether the same firms or tasks generated both movements.',
 'Automation may reduce labour requirements, but demand shifts, capital deepening and organisational restructuring can produce similar output-employment patterns.',
 'Align real value added and employment coverage over common periods. Add hours where possible and compare pre-existing trends. Use a causal label only with a defensible exposure and comparison design.',
 'Draft remains inactive pending refreshed calculations and a clear distinction from the jobs page. Changes in broad information-sector totals are not an AI treatment effect.',
 'United States information sector',
 'Matched real-output and labour-input periods',
 'Matched hours and firm/task evidence would clarify the source of output-per-worker changes.',
 ARRAY['bls-productivity','acemoglu']),

('skills-shortage',
 'Lower vacancy pressure can coexist with a growing stock of technology workers. Neither movement alone establishes that a skills shortage has eased: recruitment demand, matching and workforce supply can change independently.',
 'A vacancy rate, a share of firms reporting recruitment difficulty and an employment stock have different denominators. Seasonally unadjusted quarters should not be used to declare a unique low without matching the season and checking the full history.',
 'AI could reduce demand for some skills and increase demand for complementary ones. A weaker business cycle can also reduce vacancies without improving the supply of scarce skills.',
 'Use seasonally adjusted rates or compare equivalent quarters and rolling annual summaries. State the survey denominator for recruitment difficulty and distinguish flows of recruitment from the worker stock.',
 'Draft remains inactive until seasonal comparisons and survey populations are checked. Fewer employers recruiting is not proof that each recruiting employer finds suitable staff more easily.',
 'EU information and communication and ICT specialist populations',
 'Matched seasonal vacancy windows and separate annual survey periods',
 'Consistent recruitment-difficulty measures conditional on hiring would improve the shortage assessment.',
 ARRAY['bls-jolts','eurostat-ai']),

('ai-wages',
 'Advertised wage premiums describe selected job postings, not the earnings gain from acquiring AI skills. AI-specific requirements and a count of new skills are different treatments. Neither should be compared as though it estimated the same return.',
 'Observed premiums can reflect occupation, employer, location and applicant selection. Unit labour costs are compensation per unit of output, not hourly pay; rising unit labour costs can coexist with productivity gains when compensation rises faster.',
 'Scarce complementary skills may command a premium, while automation can reduce demand for other tasks. A posting premium does not establish that training causes the advertised wage difference.',
 'Identify the skill definition, sample, controls and wage measure for each report. Keep posting evidence separate from realised pay and national ULC. Verify extracted figures against the cited version before activation.',
 'Draft remains inactive pending claim-level report verification and comparable definitions. Associations in adverts are not causal training returns, and an aggregate wage-cost series cannot validate them.',
 'Report-specific UK/US posting samples; separately labelled wage context',
 'Each report sample and version separately; no pooled premium',
 'Matched worker outcomes or a credible skill-acquisition design would support a return-to-skills claim.',
 ARRAY['bls-productivity','acemoglu']),

('compute-price-abroad',
 'US and Japanese price indices can show how their defined service baskets changed over an overlapping period. They cannot establish that compute became dearer only in one country when coverage, contracts and end dates differ.',
 'A cloud application, data-centre service and software-development contract are not equivalent products. Index rebasing does not harmonise their quality, currency or basket definitions.',
 'Energy, labour, market structure and product quality can affect service prices differently across countries. The charts alone cannot allocate the difference to these channels.',
 'Use the common observed window and document the source base and basket. Resolve discontinued or rebased series before extending comparisons; do not carry an old Japanese endpoint forward.',
 'Draft remains inactive pending a current, comparable Japanese counterpart. Software-development prices are not simply a wage index, and hosting prices are not cost per AI task.',
 'United States and Japan, with distinct service baskets',
 'Overlapping observed periods only',
 'Current harmonised quality-adjusted service measures would support a country comparison.',
 ARRAY['bls-cloud']),

('labour-vs-compute',
 'The current indicators cannot price an hour of labour against an hour of equivalent AI work. Unit labour costs already divide compensation by output, while hosting prices cover a service basket. Their growth difference is not an estimate of the incentive to replace a worker.',
 'The substitution comparison requires comparable task output and total cost, including quality, supervision and implementation. Hourly compensation, ULC and price per compute unit must not be interchanged.',
 'A firm may substitute AI when it can deliver the required task more cheaply, or use it to complement workers. Capability and reliability matter alongside purchase prices.',
 'Use hourly compensation for labour input cost and a documented task/performance measure for compute. State quality and overhead assumptions. Keep ULC as production-cost context, not the labour-hour price.',
 'Draft remains inactive pending comparable cost measures. A relative change in two broad indices does not identify substitution elasticity or realised employment effects.',
 'United States broad labour and service-price context',
 'Matched cost periods and task definitions required',
 'A reproducible cost-per-equivalent-task comparison would answer the substitution question.',
 ARRAY['bls-productivity','bls-cloud','acemoglu']),

('when-noticed',
 'Keyword counts can date the appearance of language in federal publications, but cannot date when government first noticed AI. An apparent break may reflect changing terminology, agency coverage or repeated boilerplate rather than a new policy response.',
 'A document matches a search rule, not a verified substantive definition of AI policy. Absence of a term is not absence of attention, and publication frequency is not institutional preparedness.',
 'Technological events may increase attention, while vocabulary changes can increase recorded mentions without changing the underlying policy activity. These explanations need document-level evidence.',
 'Validate samples on both sides of apparent breaks, retain agency and term matches, and compare substantive categories. Recompute historical totals from a reproducible query before narrating a turning point.',
 'Draft remains inactive pending relevance validation and refreshed counts. Early term collisions and changes in coverage make a single first-attention date indefensible.',
 'United States federal publication corpus',
 'Full query history with validated break windows',
 'Reviewed documents around the apparent break would distinguish vocabulary from substantive policy change.',
 ARRAY['nara']),

('rules-vs-adoption',
 'The available regulatory and enterprise series cannot establish whether rules ran ahead of adoption. Their jurisdictions, populations and reporting frequencies differ, so simultaneous changes do not identify a policy response.',
 'US document counts and multi-country enterprise-use rates are not a matched panel. Compare percentage-point and proportional changes correctly; a single coincident step provides no estimate of a lead or lag.',
 'Policy can respond to adoption, encourage it or constrain it; both may instead respond to a common technology or attention shock.',
 'Match jurisdiction and period, validate the policy measure and keep survey definitions stable. Treat unmatched series as descriptive context until those requirements are met.',
 'Draft remains inactive pending a matched population and validated policy series. Document volume is not regulatory burden, and survey use does not measure deployment intensity.',
 'US federal documents versus surveyed European/OECD enterprises; currently unmatched',
 'Comparable annual periods required',
 'A jurisdiction-matched adoption-policy panel would allow the timing question to be investigated.',
 ARRAY['nara','eurostat-ai']),

('cost-of-compliance',
 'A broad hosting-price index cannot estimate the cost of AI compliance or rule out a large cost for a narrow set of firms. Costs may affect margins, entry, quality or internal work rather than appearing directly in the average selling price.',
 'An upper bound requires an explicit model, identification strategy and uncertainty or detection threshold. Comparing price growth with publication counts supplies none of these. Pass-through depends on demand and market conditions.',
 'Compliance can use resources, while clearer rules may also reduce uncertainty or improve trust. The net cost and its incidence depend on the obligations and affected firms, not the number of documents.',
 'Identify substantive obligations and effective dates, then compare exposed outcomes with a defensible counterfactual. Keep broad PPI as context and distinguish fixed compliance costs from marginal production costs.',
 'Draft remains inactive pending an identified compliance measure. A small aggregate price change cannot establish low compliance costs, and a price rise cannot attribute them to regulation.',
 'United States; affected firms and obligations not yet identified',
 'Effective-date event windows required',
 'Firm-level compliance costs and a valid comparison design would support a burden estimate.',
 ARRAY['nara','bls-cloud']);

UPDATE questions q
SET answer_plain=e.answer_plain, answer_expert=e.answer_expert,
    theory=e.theory, method=e.method, caveat=e.caveat,
    strength=CASE WHEN q.id IN ('adoption','money','building','power','materials')
                  THEN 'suggestive'::evidence_strength
                  ELSE 'insufficient'::evidence_strength END,
    last_reviewed=NULL, updated_at=now()
FROM editorial_052 e
WHERE q.id=e.id AND
 (q.answer_plain,q.answer_expert,q.theory,q.method,q.caveat)
 IS DISTINCT FROM
 (e.answer_plain,e.answer_expert,e.theory,e.method,e.caveat);

CREATE TEMP TABLE editorial_sources_052 (
 source_key TEXT PRIMARY KEY, title TEXT, publisher TEXT, url TEXT,
 version TEXT, locator TEXT, finding TEXT, method TEXT, limitations TEXT,
 access_basis TEXT, publication_stage TEXT, kind TEXT
) ON COMMIT DROP;

INSERT INTO editorial_sources_052 VALUES
('eurostat-ai',
 'Use of artificial intelligence in enterprises',
 'Eurostat',
 'https://ec.europa.eu/eurostat/statistics-explained/SEPDF/cache/106920.pdf?v=5006297249739583',
 'Statistics Explained, 2 June 2026; accessed 10 September 2026',
 'Pages 1-3 and Data sources',
 'The enterprise measure covers use of at least one AI technology in its defined business population; it does not measure task intensity.',
 'Official enterprise ICT survey statistics.',
 'Enterprise survey coverage and definitions do not apply to people or SEC disclosures.',
 'full_text',
 'official_data',
 'official'),

('bea-real',
 'Measuring Infrastructure in the Bureau of Economic Analysis National Economic Accounts',
 'Bureau of Economic Analysis',
 'https://www.bea.gov/sites/default/files/papers/BEA-WP2020-12.pdf',
 'BEA working paper 2020-12; accessed 10 September 2026',
 'Printed page 11 (PDF page 11), real investment and stocks',
 'BEA generally obtains real fixed investment by dividing nominal investment by a price index; stocks additionally depend on depreciation.',
 'National-account investment and perpetual-inventory methodology.',
 'Measurement guidance does not estimate current AI investment.',
 'full_text',
 'report',
 'official'),

('bls-productivity',
 'Handbook of Methods: Office of Productivity and Technology — Concepts',
 'Bureau of Labor Statistics',
 'https://www.bls.gov/opub/hom/opt/concepts.htm',
 'Web methodology accessed 10 September 2026',
 'Labor productivity; Capital input; How does TFP relate to labor productivity?; Unit labor costs',
 'BLS distinguishes output per hour, capital services and TFP. Unit labour costs are compensation per unit of output.',
 'Growth-accounting concepts and definitions.',
 'Accounting decomposition is not causal attribution to AI.',
 'full_text',
 'official_data',
 'official'),

('jcurve',
 'The Productivity J-Curve: How Intangibles Complement General Purpose Technologies',
 'Brynjolfsson, Rock and Syverson / NBER',
 'https://ide.mit.edu/sites/default/files/publications/jcurve.pdf',
 'NBER Working Paper 25148, October 2018 manuscript; accessed 10 September 2026',
 'Abstract (PDF page 2); conclusion (PDF page 37)',
 'Complementary intangible investment can delay measured productivity benefits. The authors explicitly state that such investment does not guarantee a J-curve.',
 'Model of intangible investment and measured productivity, with historical applications.',
 'This manuscript is not an estimate of the current AI contribution; later published versions may differ.',
 'full_text',
 'working_paper',
 'academic'),

('acemoglu',
 'The Simple Macroeconomics of AI',
 'Daron Acemoglu / Economic Policy',
 'https://economics.mit.edu/sites/default/files/2024-10/The%20Simple%20Macroeconomics%20of%20AI.pdf',
 'Economic Policy 2024 author-hosted published PDF, DOI 10.1093/epolic/eiae042; accessed 10 September 2026',
 'Summary and introduction, PDF pages 1 and 3-6',
 'The task framework links aggregate gains to affected task shares and cost savings, distinguishing automation from complementarity.',
 'Task-based model and calibrated scenarios.',
 'Its assumptions and forecasts are not current observed outcomes or universal country estimates.',
 'full_text',
 'published',
 'academic'),

('ai-work',
 'Generative AI at Work',
 'Brynjolfsson, Li and Raymond',
 'https://arxiv.org/abs/2304.11771v2',
 'arXiv version 2, revised 6 November 2024; abstract accessed 10 September 2026',
 'Version 2 abstract only',
 'A staggered workplace rollout reports productivity gains with substantial variation by worker experience and skill.',
 'Staggered introduction among customer-support agents, as described in the abstract.',
 'Abstract-only review: not a full assessment of identification, and not an employment-creation estimate.',
 'abstract',
 'working_paper',
 'academic'),

('epoch-clusters',
 'Data on GPU Clusters',
 'Epoch AI',
 'https://epoch.ai/data/gpu-clusters',
 'Dataset page accessed 10 September 2026; download labelled 13 March 2026',
 'Disclaimer; Include planned systems; Documentation',
 'The register includes a planned-systems option and warns that reporting coverage varies; planned specifications have lower confidence.',
 'Publicly documented cluster register.',
 'Coverage is incomplete; power capacity is not metered energy use or a census of operating facilities.',
 'full_text',
 'report',
 'industry'),

('iea-energy',
 'Energy and AI — Executive summary',
 'International Energy Agency',
 'https://www.iea.org/reports/energy-and-ai/executive-summary',
 '2025 report; executive summary accessed 10 September 2026',
 'Local impacts; grid integration; uncertainty sections',
 'The IEA identifies geographically concentrated data-centre demand and grid-connection constraints, and explores uncertain future demand scenarios.',
 'Global energy modelling and infrastructure analysis.',
 'Scenarios are projections; local constraints cannot be inferred from national tariff averages alone.',
 'full_text',
 'report',
 'official'),

('bls-chip',
 'A new approach for quality-adjusting PPI microprocessors',
 'Bureau of Labor Statistics',
 'https://www.bls.gov/opub/mlr/2018/article/a-new-approach-for-quality-adjusting-ppi-microprocessors.htm',
 'Monthly Labor Review, December 2018; accessed 10 September 2026',
 'Introduction and Data and methods',
 'Microprocessor pricing and quality changes can make matched-model and hedonic indices behave differently.',
 'Historical hedonic and matched-model price-index comparison.',
 'The historical microprocessor sample does not provide a current GPU or AI-task price index.',
 'full_text',
 'published',
 'official'),

('nara',
 'Federal Register Tutorial',
 'National Archives and Records Administration',
 'https://www.archives.gov/federal-register/tutorial/online-html.html',
 'Web tutorial accessed 10 September 2026',
 'Overview of Rulemaking Process; Proposed Rules; Rules and Regulations; Effective date',
 'Publication and effective dates differ. Document categories contain actions beyond new obligations, and proposals must be followed through their histories.',
 'Official description of the federal publication and rulemaking process.',
 'Methodology does not validate AI keyword relevance or estimate regulatory burden.',
 'full_text',
 'official_data',
 'official'),

('bls-cps',
 'Concepts and Definitions (CPS)',
 'Bureau of Labor Statistics',
 'https://www.bls.gov/cps/definitions.htm',
 'Web definitions accessed 10 September 2026',
 'Employed; Unemployed; Civilian labor force; Unemployment rate',
 'Employment, unemployment and labour-force participation refer to different populations and denominators.',
 'Household labour-market statistical definitions.',
 'US definitions alone do not harmonise international surveys or occupational classifications.',
 'full_text',
 'official_data',
 'official'),

('eurostat-power',
 'Electricity prices — bi-annual data: metadata',
 'Eurostat',
 'https://ec.europa.eu/eurostat/cache/metadata/en/nrg_pc_204_sims.htm',
 'SIMS metadata accessed 10 September 2026',
 'Statistical concepts and definitions; Data compilation',
 'National electricity prices are weighted averages; Eurostat aggregates national prices using consumption weights.',
 'Official electricity-price collection and aggregation methodology.',
 'Aggregate band comparisons can change with composition; they do not follow the same buyer.',
 'full_text',
 'official_data',
 'official'),

('bls-cloud',
 'Exploring quality adjustment in PPI cloud computing',
 'Bureau of Labor Statistics',
 'https://www.bls.gov/opub/mlr/2023/article/exploring-quality-adjustment-in-PPI-cloud-computing.htm',
 'Monthly Labor Review, February 2023; accessed 10 September 2026',
 'Opening summary; Industry and index background',
 'The study examines cloud quality adjustment and explains that hosting is one component of the broader data-processing price index.',
 'Hedonic cloud-service models using public provider data.',
 'Research models are not evidence that the current official index implements the proposed adjustment.',
 'full_text',
 'published',
 'official'),

('sec-finance',
 'Beginners’ Guide to Financial Statements',
 'US Securities and Exchange Commission',
 'https://www.sec.gov/investor/pubs/begfinstmtguide.htm',
 '4 February 2007 guide; accessed 10 September 2026',
 'Cash Flow Statements; Operating, Investing and Financing Activities',
 'Cash-flow statements distinguish operating cash, asset investment and financing from debt or equity.',
 'Official guide to financial-statement interpretation.',
 'It supplies accounting definitions, not evidence of how AI firms currently fund investment.',
 'full_text',
 'official_data',
 'official'),

('bls-jolts',
 'Job Openings and Labor Turnover Survey — Data Definitions',
 'Bureau of Labor Statistics',
 'https://www.bls.gov/jlt/jltdef.htm',
 'Web definitions accessed 10 September 2026',
 'Job openings; Hires; Separations',
 'Job openings are a stock at a reference date, whereas hires and separations measure flows over a period.',
 'Official labour-demand survey definitions.',
 'US JOLTS definitions do not establish comparability with every international vacancy series.',
 'full_text',
 'official_data',
 'official');

-- Exact access basis remains visible. The old enum's 'reviewed' means human
-- checked; these takeaways deliberately use 'extracted' until reviewed.
INSERT INTO question_reading
 (question_id,title,publisher,url,kind,stance,takeaway,
  takeaway_source,takeaway_ref,sort_order,review_actor)
SELECT e.id,s.title,s.publisher,s.url,s.kind::reading_kind,
       'background'::reading_stance,s.finding,
       'extracted'::takeaway_source,
       s.version || '; ' || s.locator || '; access: ' || s.access_basis ||
       '; agent-authored source note, not human-reviewed.',
       -10,'agent'
FROM editorial_052 e
JOIN editorial_sources_052 s ON s.source_key=ANY(e.source_keys)
ON CONFLICT (question_id,lens_id,url) DO UPDATE SET
 title=EXCLUDED.title,publisher=EXCLUDED.publisher,kind=EXCLUDED.kind,
 stance=EXCLUDED.stance,takeaway=EXCLUDED.takeaway,
 takeaway_source=EXCLUDED.takeaway_source,takeaway_ref=EXCLUDED.takeaway_ref,
 sort_order=EXCLUDED.sort_order,review_actor=EXCLUDED.review_actor
-- Do not overwrite a later human-checked source interpretation.
WHERE question_reading.takeaway_source IS DISTINCT FROM 'reviewed'::takeaway_source;

-- Every replaced argumentative field is represented, not only the headline.
-- These are section-level claims, with unresolved empirical checks made explicit.
INSERT INTO research_claims
 (id,question_id,statement,claim_type,verdict,geography,period,limitations,change_trigger)
SELECT 'editorial-20260910-' || e.id || '-' || f.field,
       e.id,f.statement,f.claim_type,
       CASE WHEN f.field='mechanism' THEN 'unresolved' ELSE 'qualified' END,
       e.geography,e.period,e.caveat,e.change_trigger
FROM editorial_052 e
CROSS JOIN LATERAL (VALUES
 ('finding',e.answer_plain,'descriptive'),
 ('expert',e.answer_expert,'descriptive'),
 ('mechanism',e.theory,'mechanism'),
 ('method',e.method,'descriptive')
) f(field,statement,claim_type)
ON CONFLICT (id) DO UPDATE SET
 statement=EXCLUDED.statement,claim_type=EXCLUDED.claim_type,
 verdict=EXCLUDED.verdict,geography=EXCLUDED.geography,period=EXCLUDED.period,
 limitations=EXCLUDED.limitations,change_trigger=EXCLUDED.change_trigger;

INSERT INTO research_evidence
 (id,claim_id,source_url,source_title,source_version,locator,finding,method,
  limitations,relationship,relevance,access_basis,publication_stage)
SELECT 'editorial-20260910-' || e.id || '-' || f.field || '-' || s.source_key,
       'editorial-20260910-' || e.id || '-' || f.field,
       s.url,s.title,s.version,s.locator,s.finding,s.method,s.limitations,
       'context',
       'Scope and method for ' || e.id || ': ' || e.change_trigger ||
       ' This source is context for the stated reasoning, not verification of every chart observation.',
       s.access_basis,s.publication_stage
FROM editorial_052 e
JOIN editorial_sources_052 s ON s.source_key=ANY(e.source_keys)
CROSS JOIN (VALUES ('finding'),('expert'),('mechanism'),('method')) f(field)
ON CONFLICT (id) DO UPDATE SET
 source_url=EXCLUDED.source_url,source_title=EXCLUDED.source_title,
 source_version=EXCLUDED.source_version,locator=EXCLUDED.locator,
 finding=EXCLUDED.finding,method=EXCLUDED.method,limitations=EXCLUDED.limitations,
 relationship=EXCLUDED.relationship,relevance=EXCLUDED.relevance,
 access_basis=EXCLUDED.access_basis,publication_stage=EXCLUDED.publication_stage;

-- Atomic high-risk claims: these corrections are independently locatable.
CREATE TEMP TABLE editorial_atomic_052
 (atom TEXT,question_id TEXT,statement TEXT,source_key TEXT,relationship TEXT,relevance TEXT)
 ON COMMIT DROP;
INSERT INTO editorial_atomic_052 VALUES
('deflator-direction','money','For a matched asset, falling prices make real-investment growth exceed nominal-investment growth, other things equal.','bea-real','supports','Applying real investment = nominal investment / price index reverses the old deflator claim.'),
('capital-deepening','money','Investment spending is not capital deepening: the latter concerns capital input relative to labour input.','bls-productivity','supports','BLS separates investment flows, capital services and capital deepening.'),
('orders-deflation','orders-and-output','A lower nominal orders value than an earlier peak is insufficient to conclude that real orders are lower.','bea-real','supports','A volume comparison requires the relevant price adjustment; the inference is an application of that accounting identity.'),
('ulc-definition','labour-vs-compute','Unit labour costs measure compensation per unit of output, not the price of an hour of labour.','bls-productivity','supports','The ULC definition directly corrects the draft''s hourly-cost interpretation.'),
('ulc-and-productivity','ai-wages','Unit labour costs can rise while labour productivity rises if hourly compensation grows faster.','bls-productivity','supports','ULC is hourly compensation divided by output per hour; both numerator and denominator can rise.'),
('capital-contributions','computer-dividend','A software capital-stock-growth contribution and an ICT labour-productivity-growth contribution are not a matched estimate of investment returns.','bls-productivity','context','Growth-accounting definitions identify the different denominators; the incompatibility is our analytical deduction.'),
('publication-effective','policy','The publication of a federal rule does not imply that it becomes effective on the publication date.','nara','supports','The rulemaking tutorial distinguishes publication, effective dates and exceptions.'),
('proposal-cohorts','rule-conversion','Annual final-rule and proposal counts cannot yield a conversion rate without following linked actions over time.','nara','context','The tutorial sets out the sequence; cohort-linkage requirements are our statistical inference.'),
('capacity-status','building','The public GPU-cluster register can include planned systems, so unfiltered capacity is not a total of verified operating capacity.','epoch-clusters','supports','The source''s planned-systems option and uncertainty disclaimer directly constrain aggregation.'),
('hosting-basket','markets','The broad data-processing price index is not a pure constant-quality price for a unit of AI computation.','bls-cloud','supports','BLS describes the aggregate basket and the quality-adjustment problem.'),
('workplace-complementarity','entry-level','The November 2024 Generative AI at Work abstract reports heterogeneous workplace productivity gains, not an estimate of entry-level hiring effects.','ai-work','supports','This abstract is a counterpoint on worker complementarity, not evidence that aggregate employment rises.'),
('jcurve-not-guaranteed','productivity','Complementary intangible investment does not guarantee a later measured productivity boom.','jcurve','supports','The manuscript conclusion explicitly rejects a guaranteed J-curve.'),
('financing-versus-use','who-funds-it','Capital expenditure is an investing use of cash, distinct from cash supplied by operating or financing activities.','sec-finance','supports','The SEC guide separates the cash-flow statement''s three sections.'),
('band-composition','bulk-discount','Electricity-price group averages can differ because of weights and composition as well as buyer scale.','eurostat-power','context','The aggregation documentation supports the statistical caution, not a quantified causal decomposition.');

INSERT INTO research_claims
 (id,question_id,statement,claim_type,verdict,geography,period,limitations,change_trigger)
SELECT 'editorial-20260910-atomic-'||a.atom,a.question_id,a.statement,
       'descriptive','qualified',e.geography,e.period,
       s.limitations,e.change_trigger
FROM editorial_atomic_052 a
JOIN editorial_052 e ON e.id=a.question_id
JOIN editorial_sources_052 s ON s.source_key=a.source_key
ON CONFLICT(id) DO UPDATE SET
 statement=EXCLUDED.statement,verdict=EXCLUDED.verdict,
 limitations=EXCLUDED.limitations,change_trigger=EXCLUDED.change_trigger;

INSERT INTO research_evidence
 (id,claim_id,source_url,source_title,source_version,locator,finding,method,
  limitations,relationship,relevance,access_basis,publication_stage)
SELECT 'editorial-20260910-atomic-'||a.atom||'-source',
       'editorial-20260910-atomic-'||a.atom,
       s.url,s.title,s.version,s.locator,s.finding,s.method,s.limitations,
       a.relationship,a.relevance,s.access_basis,s.publication_stage
FROM editorial_atomic_052 a
JOIN editorial_sources_052 s ON s.source_key=a.source_key
ON CONFLICT(id) DO UPDATE SET
 source_url=EXCLUDED.source_url,source_title=EXCLUDED.source_title,
 source_version=EXCLUDED.source_version,locator=EXCLUDED.locator,
 finding=EXCLUDED.finding,method=EXCLUDED.method,limitations=EXCLUDED.limitations,
 relationship=EXCLUDED.relationship,relevance=EXCLUDED.relevance,
 access_basis=EXCLUDED.access_basis,publication_stage=EXCLUDED.publication_stage;

-- Known caption errors identified in the staging snapshot on 10 September.
-- Keep the specific indicator role visible; do not replace every caption with
-- a generic disclaimer. Other numeric captions remain on the verification list.
WITH corrections(question_id,indicator_id,plain,expert) AS (VALUES
 ('adoption','derived.sec_ai_mention_rate',
  'AI mentions in US corporate filings measure disclosure, not verified use. They are context for the enterprise-adoption survey.',
  'Compare the matched-filings numerator with the defined filings denominator. Risk disclosures, plans and operational use can all mention AI; verify coverage and quarterly aggregation before quoting a company share.'),
 ('money','dbn.BEA.NIPA-T50405.LA001282-A',
  'Spending on data-centre structures narrows the investment measure to buildings, excluding the servers inside. It cannot rank this category against the whole national accounts.',
  'BEA NIPA structures investment. Interpret nominal expenditure and the observed coverage window separately from equipment, operating capacity and real investment.'),
 ('policy','derived.ai_binding_rules',
  'Federal Register documents in the Rule category. Publication counts do not establish how many AI obligations are currently in force.',
  'Retain action and effective dates and validate substantive AI relevance. A rule-category record may amend or withdraw an earlier action; a keyword match does not establish legal burden.'),
 ('cost-of-compliance','derived.ai_regulation_volume',
  'All matching publications provide context for regulatory activity. A larger document count is not a measure of compliance costs.',
  'Notices, requests and guidance have different functions. Identify obligations and affected firms before using this series as a treatment measure.'),
 ('dot-com','fred.B985RC1Q027SBEA',
  'Software investment is a component of the broader ICT investment series. Their common accounting basis permits a composition comparison.',
  'BEA national accounts treat software as an investment asset. Do not infer corporate expensing treatment from this series or equate software investment with unmeasured complementary intangibles.'),
 ('policy-lag','derived.ai_presidential_documents',
  'Presidential publications show a separate policy instrument. Their timing can be described without assuming they always lead agency action.',
  'Document type does not determine the duration, implementation speed or legal effect of each action. Inspect its content and linked implementing measures.'),
 ('sector-output','fred.RVASPI',
  'Private services provide a broad output comparator. This aggregate is not an untreated control group and should not be labelled everything except information.',
  'Check the aggregate industry coverage and compare matched real-growth windows. Shared national conditions do not imply identical shocks across constituent sectors.')
)
UPDATE question_indicators qi
SET caption_plain=c.plain,caption_expert=c.expert
FROM corrections c
WHERE qi.question_id=c.question_id AND qi.indicator_id=c.indicator_id
  AND (qi.caption_plain,qi.caption_expert) IS DISTINCT FROM (c.plain,c.expert);
